META-39: Set up GraphQL client using urql
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #10
Opened 2023-05-13 00:25 UTC by cnk1dev

## Description of issue
## How I implemented
## Other

2023-05-13 22:46 UTC, pczern commented on .eslintrc.js
> +    node: true
let me know why `node: true`

2023-05-13 22:50 UTC, pczern commented on .eslintrc.js
> +      'error',
have a look at Arnos PR, there it is done a little different

2023-05-13 22:50 UTC, pczern commented on .eslintrc.js
> +    'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }],
we should always use warning level 2

2023-05-13 22:50 UTC, pczern commented on src/graphql/repositories.graphql
> +query GitRepositories {
we should call the file `gitRepositories` if it contains one query

2023-05-13 22:53 UTC, pczern commented
https://dev.to/xcanchal/automatically-generate-typescript-types-for-your-graphql-api-1fah article to understand GraphQL codegen

2023-05-13 22:54 UTC, pczern commented on README.md
> +Removes redunant import statements of `react` in components.
typo `redundant`

2023-05-13 22:55 UTC, pczern commented on src/pages/_app.tsx
>    return <Component {...pageProps} />
this was also done in Arnos PR

2023-05-13 22:55 UTC, pczern commented on src/pages/_app.tsx
>    return <Component {...pageProps} />
same way

2023-05-13 22:58 UTC, pczern commented on src/util/constants.ts
> +export const BASE_URL = process.env.BASE_URL || 'http://localhost:3000/graphql'
there is a `constants` folder, we shouldn't put in `util` folder

2023-05-13 23:02 UTC, cnk1dev commented on .eslintrc.js
> +    node: true
<img width="584" alt="Screenshot 2023-05-14 at 01 01 34" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/dfb9ad7f-dc6c-4e48-a5d6-528d3da1889a">

@pczern

2023-05-13 23:02 UTC, cnk1dev commented on .eslintrc.js
> +      'error',
ok, we can just use Arno's version then when we merge

2023-05-13 23:07 UTC, cnk1dev commented on src/pages/_app.tsx
>    return <Component {...pageProps} />
ok, should not be an issue when we merge then

2023-05-14 12:26 UTC, pczern commented on .eslintrc.js
> +    node: true
I think it is better to use 
```
 "globals": {
        "process": true
      }
```

2023-05-14 12:28 UTC, pczern commented on .eslintrc.js
> +    node: true
or take a look at this, if it's up to date https://stackoverflow.com/a/76081175

2023-05-14 12:33 UTC, pczern requested changes
Please change to globals process or import globals like in the stackoverflow link,
give further explanation about Codegen and how gitRepositories.tsx is generated

2023-05-14 12:33 UTC, pczern commented on src/pages/_app.tsx
> +    exchanges: [cacheExchange, ssrExchange, fetchExchange]
in what case do we need ssrExchange?

2023-05-14 12:33 UTC, pczern commented on src/pages/_app.tsx
> +    exchanges: [cacheExchange, ssrExchange, fetchExchange]
I think we could do a pretty basic non ssr setup at the moment, this might then even be a lot faster for page load

2023-05-14 12:52 UTC, cnk1dev commented on .eslintrc.js
> +    node: true
done

2023-05-14 13:01 UTC, cnk1dev commented on src/pages/_app.tsx
> +    exchanges: [cacheExchange, ssrExchange, fetchExchange]
Are you sure CSR would be faster? Afaik initial page load is faster with SSR than CSR, but subsequent page loads are faster with CSR. Neither setup is very complex with urql though, so if we make the decision to use CSR we can easily change it. But then again, what are we using Next for?

2023-05-14 13:02 UTC, cnk1dev commented on src/pages/_app.tsx
> +    exchanges: [cacheExchange, ssrExchange, fetchExchange]
The codegen command is explained in the readme, all it does is create types and a custom hook for each query

2023-05-14 21:23 UTC, cnk1dev commented on src/pages/_app.tsx
> +    exchanges: [cacheExchange, ssrExchange, fetchExchange]
Removed ssrExchange

2023-05-16 18:07 UTC, pczern approved these changes
If `ts-node` is not needed please remove, otherwise please merge

2023-05-16 18:14 UTC, merged