FRONT-60 Detail page
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #11
Opened 2023-05-13 10:32 UTC by DamianGrosz2

## Description of Issue

Code the detail page, which includes several elements such as a sidebar on the right and left, a navigation bar at the top, project information, a diagram for stars, and cards for tweets/community sentiment.

## How I implemented

The main elements of the page have been broken down into individual components to promote reusability and maintainability. Here's a brief overview of the component structure:

- **Right Sidebar**: This sidebar currently has two entries. A saved searches tab is also included in the sidebar.
- **Navigation Bar**: A navigation bar is present at the top of the page.
- **Project Information**: Project-specific information is displayed in a dedicated component.
- **Diagram**: A diagram component has been built to visually represent various data points such as stars, forks, and issues. This component utilizes the recharts library for creating interactive and responsive charts.
- **Cards** for Tweets/Community Sentiment: These cards display data related to the social sentiments towards the project.
- **Left Sidebar**: This sidebar houses various project statistics. Each statistic is encapsulated within its own component for better separation of concerns.
- For more information on the reusable components that were created, please refer to the documentation in [Notion](https://www.notion.so/Reusable-Frontend-components-82b6640878b2490499d508adf57b0560?pvs=4).

## Other

The overview page bundles all of those components for now. It is not yet ion a clean code manner.
Also the Chart component can be improved. Both of those files need additional context (how does the data look like etc.).

Please review the PR and provide your feedback.

2023-05-13 20:12 UTC, cnk1dev requested changes
Components generally look good, a few style issues can be improved later on, but the following things need to be done before merging:

- [ ] Fix all eslint errors (200+ problems, many of them might be solvable with --fix option)
- [x] Make sure the build runs successfully (check out the Vercel deployment logs)
- [x] Remove unused icons folder

2023-05-14 12:48 UTC, cnk1dev requested changes
Please resolve merge conflicts in tailwind config and global styles

2023-05-14 12:57 UTC, pczern requested changes
Very good work, some updates are needed
More explanation about tech choices, libraries,
Please write me on Slack when changes are implemented.
Also please smaller PRs with at most 15 files.

2023-05-14 12:57 UTC, pczern commented on package.json
> +    "react-feather": "^2.0.10",
I think this package should be removed, as `react-icons` includes it

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  let buttonStyle = ''
use a Map

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  let buttonStyle = ''
see PR from Arno

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  textColor = 'text-text-secondary',
who created these classes `text-text-secondary`? It is meant to be called `text-secondary`

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  textColor = 'text-text-secondary',
Speak with Arno about how to fix the color scheming, he has the same thing going on, I think he will fix it and then we can merge it with this PR

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  text: '',
use `null`

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  Icon: undefined,
use `null`

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  text: '',
or remove it from defaultProps

2023-05-14 12:57 UTC, pczern commented on src/components/Button.tsx
> +  Icon: undefined,
props not passed are undefined

2023-05-14 12:57 UTC, pczern commented on src/components/DetailPage/Card.tsx
> +  Icon: ComponentType<{ className?: string }>
I think JSX.Element might be better or JSXElementConstructor see https://react-typescript-cheatsheet.netlify.app/docs/advanced/types_react_api/#typesreact

2023-05-14 12:57 UTC, pczern commented on src/components/DetailPage/Card.tsx
> +      <h2 className="">{name}</h2>
useless className prop

2023-05-14 12:57 UTC, pczern commented on tailwind.config.js
> +        'bg-primary': '#191A23',
speak with Arno about colors, but having `bg-bg-...` classes is not the way to go

2023-05-14 12:57 UTC, pczern commented on package.json
> +    "date-fns": "^2.30.0",
I need an explanation of the different libraries in the PR

2023-05-14 17:25 UTC, ArnoClaude commented on src/components/Button.tsx
> +  textColor = 'text-text-secondary',
@DamianGrosz2 I've added color codes to the main branch. I've used the colors from the [Linear](https://www.figma.com/file/8YtjvVMikUG5aBl73t7xFz/Linear-Design-System-(Community)?node-id=8-2&t=6r3YUXN1Xo3eTOxG-0) design system, as well as the official [Tailwind](https://tailwindcss.com/docs/customizing-colors) colors for Gray 50 - 950 and Indigo 50 - 950.

2023-05-14 17:26 UTC, ArnoClaude commented on src/components/Button.tsx
> +  textColor = 'text-text-secondary',
Lmk if those will be enough colors for our app (I think yes). And then, let's use these color codes, such that we can keep a consistent style and naming going onward :)

2023-05-15 10:19 UTC, pczern requested changes
Too many files, PR too big
Resolve merge conflicts, make sure tests pass
Then PR get another review

2023-05-16 12:10 UTC, cnk1dev requested changes
Please also address unresolved comments from @pczern and run build locally to fix errors

2023-05-16 12:10 UTC, cnk1dev commented on src/pages/DetailPage/ProjectInformation.tsx
> +          console.log('clicked')
```suggestion
```

2023-05-16 12:10 UTC, cnk1dev commented on src/pages/loading.tsx
> +/* eslint-disable no-console */
```suggestion
```

2023-05-16 12:10 UTC, cnk1dev commented on src/pages/loading.tsx
> +              console.log('Navigation successful!')
Remove console.log statements

2023-05-16 12:10 UTC, cnk1dev commented on src/pages/overview.tsx
> +    console.log('Menu item clicked')
```suggestion
    // Menu item clicked
```

2023-05-16 12:15 UTC, cnk1dev commented on src/pages/overview.tsx
> +                  name="Community sentiment"
@ArnoClaude it's not top hackernews posts though, it is indeed supposed to be a summary of the community sentiment

2023-05-16 15:32 UTC, ArnoClaude commented
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/8a3555e4-dc91-4ae9-90aa-713b968a659e)

Let's put the buttons above the chart, and we can figure out how to use the empty space on the right later. Right now, the buttons look awkwardly placed.
Also, remove the "value" indication, it doesn't provide any value (badum-tss).
And for the date, smth. like "Apr 2023" would be more readable.

2023-05-16 20:05 UTC, cnk1dev approved these changes

2023-05-16 22:30 UTC, merged

2023-05-17 15:27 UTC, pczern reviewed
New review

2023-05-17 15:27 UTC, pczern commented on src/components/DetailPage/ProjectInformation.tsx
> +            key={text}
text is not a key

2023-05-17 15:27 UTC, pczern commented on src/pages/loading.tsx
> +        <div />
the div's are missing the keys

2023-05-17 15:27 UTC, pczern commented on src/components/RightSidebar/SocialMediaItem.tsx
> +        <span className="text-xs not-italic leading-3 text-gray-500">{name + text}</span>
something not right here, there is no space or anything, could be one prop

2023-05-18 15:39 UTC, pczern commented on package.json
> +    "@primer/octicons-react": "^19.1.0",
they have a PR for @primer octicons but it's not merged yet

2023-05-18 15:39 UTC, pczern commented on package.json
> +    "@primer/octicons-react": "^19.1.0",
will use this package