Spotlight impl
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #13
Opened 2023-05-15 10:47 UTC by DogukanGun

Description of Issue

An interface has been added where the user can enter their commands quickly on any desired page.

How I implemented
A component named "Spotlight" has been created to capture user input. Once the input is received, it will be processed after documentation is prepared and the commands to be executed are determined. By adding this component to the main page, when the user presses the "Ctrl + L" keys, the search component will appear, and when they press the "Esc" key, the component will close. The main page is created using the useEffect hook, similar to how it would be done with a constructor. The logic inside the useEffect hook will be executed, where the user's button presses will be checked. When the page is closed, the control operation will be terminated.

Please review the PR and provide your feedback

2023-05-15 22:02 UTC, cnk1dev requested changes

2023-05-15 22:02 UTC, cnk1dev commented on src/components/Spotlight/spotlight.tsx
Rename folder + component to CommandInterface (Spotlight is proprietary term from Apple) and file to index.tsx

2023-05-15 22:02 UTC, cnk1dev commented on src/styles/globals.css
Remove custom CSS classes and use Tailwind classes

2023-05-17 08:10 UTC, ArnoClaude requested changes

2023-05-17 15:55 UTC, pczern requested changes
There are Tailwind class problems from previous PR, merge with `main` please

2023-05-18 10:02 UTC, DogukanGun commented on src/components/Spotlight/spotlight.tsx
Fixed

2023-05-18 10:02 UTC, DogukanGun commented on src/styles/globals.css
Fixed

2023-05-18 10:02 UTC, DogukanGun commented on src/pages/index.tsx
Fixed

2023-05-18 10:04 UTC, DogukanGun commented on src/pages/index.tsx
> +  const [openModel, setOpenModel] = useState(false)
fixed

2023-05-18 22:48 UTC, pczern commented on src/styles/globals.css
> +#spotlight_wrapper {
@ArnoClaude we will migrate to css files, but with Tailwind classes. Consistency is good practice.

2023-05-20 16:56 UTC, ArnoClaude commented on src/pages/index.tsx
> +  const [openModel, setOpenModel] = useState(false)
@DogukanGun Feel free to hit "Resolve conversation" to make the PR less messy :)

2023-05-21 16:00 UTC, pczern requested changes
Branch has merge conflicts, please resolve them for next review
converting back to Draft

2023-05-24 20:47 UTC, pczern commented
@DogukanGun merge conflicts were resolved wrong, there is nothing wrong as far as I know on the frontend with linting and tests. `components` are in new folders according to their designation. See the guidelines.

2023-05-25 18:57 UTC, cnk1dev commented on src/pages/index.tsx
I meant using event.metaKey so that the shortcut for Mac users would be Cmd+K and for Windows it would be Ctrl+K. This is the convention for most web app command interfaces like this. If you do that, you might have to disable some browser-specific shortcuts though.

2023-05-28 19:33 UTC, cnk1dev commented
<img width="1221" alt="Screenshot 2023-05-28 at 21 32 46" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/8c5c90e8-0ffe-41a6-83de-a826e7d4a4ce">

2023-05-29 14:08 UTC, cnk1dev requested changes
Please address the following things:
- Use event.metaKey + K as event listener as described in the comment below
- Center command interface + style exactly according to Figma mockups

2023-05-29 14:08 UTC, cnk1dev commented on src/pages/index.tsx
still relevant

2023-05-30 08:45 UTC, pczern requested changes

2023-05-30 08:45 UTC, pczern commented on src/components/CommandInterface/CommandInterface.tsx
> +  const [searchWord, setSearchWord] = React.useState<string>('')
is this not implicitly typed?

2023-05-30 08:45 UTC, pczern commented on src/components/CommandInterface/CommandInterface.tsx
> +    if (inputRef && inputRef.current) {
if(inputRef?.current)

2023-06-01 20:31 UTC, DogukanGun commented on src/pages/index.tsx
fixed

2023-06-02 08:47 UTC, cnk1dev requested changes
Event listener is correct now, but styles are still very different from Figma. Please also address the open change requests from @pczern and solve merge conflicts with main again.

2023-06-02 20:19 UTC, DogukanGun commented on src/pages/index.tsx
> +    function handleKeyDown(event: KeyboardEvent) {
If user open the command interface but does not search anything the list of recommendation is hidden

2023-06-02 20:20 UTC, DogukanGun commented on src/components/CommandInterface/CommandInterface.tsx
> +        {recommendationIsOpen && (
If user open the command interface but does not search anything the list of recommendation is hidden

2023-06-02 20:20 UTC, DogukanGun commented on src/pages/index.tsx
> +    function handleKeyDown(event: KeyboardEvent) {
Did you mean putting handleKeyDown outside of the home component? If you ask this, could you provide me an example?

2023-06-02 20:21 UTC, DogukanGun commented on src/components/CommandInterface/CommandInterface.tsx
> +            <li className="cursor-pointer px-4 py-2 hover:bg-gray-900">Result 1</li>
I will handle it when this pr is approved. First part is the design and basic features of command interface then I will start recommendation and in final i will implement navigation feature.

2023-06-02 20:23 UTC, DogukanGun commented on src/components/CommandInterface/CommandInterface.tsx
> +  const [searchWord, setSearchWord] = React.useState<string>('')
This was the solution that commit want me to do, otherwise I was not able to push. If you dont want to keep this code please change the commit checks.

2023-06-04 12:44 UTC, cnk1dev requested changes

2023-06-04 12:44 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
The command interface is still not centered and the design doesn't correspond to the mockups in Figma. Please refer to the screenshots below to see how it currently looks and what it should look like:

<img width="736" alt="Screenshot 2023-06-04 at 14 33 33" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/622f4189-1bed-4ef6-8ebe-50a4b8362f26">
<img width="756" alt="Screenshot 2023-06-04 at 14 33 44" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/b5af12dd-e738-49f3-8b1a-f0fd6fc7fd87">

2023-06-04 12:44 UTC, cnk1dev commented on src/pages/index.tsx
When I do Cmd/ Ctrl + K, the command interface only shows after a few seconds and the site becomes extremely laggy for some reason. Can you or someone else confirm if this is the case for them too?

2023-06-05 16:19 UTC, pczern commented on src/components/CommandInterface/CommandInterface.tsx
> +        {recommendationIsOpen && (
it would be cool if we can have the list of recommendations supplied like in the image from @cnk1dev via props, and based on that render items. The PR is still small, and the design needs to be adjusted still, so maybe we can do a new component for the entries and adjust the styles

2023-06-05 16:22 UTC, pczern commented on src/pages/index.tsx
> +    function handleKeyDown(event: KeyboardEvent) {
let's put it outside of the useEffect if possible

2023-06-05 16:33 UTC, pczern commented on src/components/CommandInterface/CommandInterface.tsx
> +  const [searchWord, setSearchWord] = React.useState<string>('')
i have run this without type without issue, I think you need to delete eslint cache

2023-06-06 13:55 UTC, DogukanGun commented on src/components/CommandInterface/CommandInterface.tsx
<img width="628" alt="Screenshot 2023-06-06 at 16 40 50" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/59707019/cb5285ab-33a2-4d24-b55a-3760dfaaecbe">

This is the new design. I know there are huge differences between the design and image top. Could you help me to fix the desing?

2023-06-06 13:59 UTC, DogukanGun commented on src/pages/index.tsx
You are right. After table component is added the command interface cannot be opened. When I remove the table component the command interface is working well. Something in table component might effect the command interface.

2023-06-06 19:39 UTC, cnk1dev requested changes
Looks better now, still not quite done yet.
- Have a look at this [Tailwind Cheatsheet](https://nerdcave.com/tailwind-cheat-sheet) and try to get the styles right (use SASS if necessary)
- Update the file structure as described in the comments below
- Please don't commit with `--no-verify` next time, there were a lot of TypeScript/ Tailwind errors that would have been caught by the precommit hook
- Regarding the projects table issue, there seems to be a general problem with that which is unrelated to the command interface, so just ignore it for now (maybe develop on a page where it isn't used)

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
> +} from '@/components/commandinterface/CommandInterfaceRecommendationRow'
```suggestion
} from '@/components/CommandInterface/CommandInterfaceRecommendationRow'
```

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
> +import CommandIntefaceDivider from '@/components/commandinterface/CommandInterfaceDivider'
```suggestion
import CommandIntefaceDivider from '@/components/CommandInterface/CommandInterfaceDivider'
```

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
> +    // TODO Run search
```suggestion
    // @TODO Run search
```

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
> +          className="text-gray bg-blue-950 mt-28 block h-14 w-full appearance-none rounded-t-xl bg-gray-900 bg-left-bottom bg-no-repeat
Fix invalid Tailwind classes, if you haven't already install [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) for VS Code (see Readme for recommended extensions) - that should show you the errors

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
> +            {defaultList.map((commandInterfaceRecommendationRowType) => (
Fix type error

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterfaceDivider.tsx
You don't need a separate component for one div

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterfaceRecommendationRow.tsx
> +    {Subtitle && <h4 className="text-m mt-2 p-4 py-2 text-gray-500">{Subtitle}</h4>}
Fix invalid Tailwind class

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterfaceRecommendationRow.tsx
> +        <span className="text-m">{MenuText}</span>
Fix invalid Tailwind class

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterfaceRecommendationRow.tsx
Rename to RecommendationRow.tsx

2023-06-06 19:39 UTC, cnk1dev commented on src/components/pure/ProjectsTable/index.tsx
Move event handler + modal to `src/components/side-effects/Page/index.tsx` so that it works on all pages

2023-06-06 19:39 UTC, cnk1dev commented on src/pages/index.tsx
> +
```suggestion
```

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
Rename to `index.tsx`, the component name is already in the folder. Also, move the entire `CommandInterface` folder into the `side-effects` folder

2023-06-06 19:39 UTC, cnk1dev commented on src/components/CommandInterface/CommandInterface.tsx
It should be possible to implement the design using Tailwind. [This cheatsheet](https://nerdcave.com/tailwind-cheat-sheet) might be helpful for that. If you tried everything and still can't get it to work using only Tailwind classes, you can create an additional `index.module.sass` file in the CommandInterface and use custom SASS to style the rest.

2023-06-07 12:51 UTC, DogukanGun commented on src/components/CommandInterface/CommandInterface.tsx
> +            {defaultList.map((commandInterfaceRecommendationRowType) => (
I did not get any type error, could you show where the type error is.

2023-06-08 22:25 UTC, kigadye requested changes
Looking much better now, but still some things that need to be improved

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/RecommendationRow.tsx
> +  Subtitle?: string | null
Use camelCase for primitive values (first letter lowercase)

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +  TruffleAiCommand: TruffleAiCommand
Use camelCase for primitive values (first letter lowercase)

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +import TruffleAiCommand from './truffle_ai_command'
Order inputs (first packages, then components, then data)

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +  const [recommendationList, setRecommendationList] = React.useState<RecommendationRowType[]>([])
Import useState directly from react (`import { useState } from 'react'`)

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +  ]
Move this to a separate file to keep the component small

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +    })
Don't need to catch exception, `router.push` usually doesn't cause any errors afaik

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +          {recommendationList.map((commandInterfaceRecommendationRowType) => (
Rename `commandInterfaceRecommendationRowType` to `item` or something like that, no need to use 30 letter long variable names

2023-06-08 22:25 UTC, kigadye commented on src/pages/index.tsx
Why did you remove this comment?

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/truffle_ai_command.ts
Rename to `CommandInterfaceOptions`

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +            className="bg-blue-950 mt-28 block h-14 w-full appearance-none rounded-t-xl bg-gray-900 bg-left-bottom bg-no-repeat px-6
The design looks much better now, if you fix the following things it should be perfect:

- [ ] Give the modal a fixed width
- [ ] Center it horizontally (remove the `pr-40` class)
- [ ] Increase the height and hide the scrollbar in the results list

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +  }
I think this method will have to get a bit more complex, for example for the details and compare pages, we can't just redirect to /details/:id, we should probably do something like when the user types details, we run a query for all projects the user has bookmarked and show them in the command interface list, and then the user clicks on one of them and only then gets redirected

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +  }
Also for the email link, the result item shouldn't redirect to any page but directly be an <a> tag with mailto href attribute that immediately opens the user's email program when clicked

2023-06-08 22:25 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +            className="bg-blue-950 mt-28 block h-14 w-full appearance-none rounded-t-xl bg-gray-900 bg-left-bottom bg-no-repeat px-6
Remove invalid Tailwind class (`bg-blue-950`)

2023-06-09 08:49 UTC, DogukanGun commented on src/pages/index.tsx
Which comment?

2023-06-09 08:50 UTC, DogukanGun commented on src/components/side-effects/CommandInterface/index.tsx
> +    })
Catch was recommended by lint.

2023-06-11 18:17 UTC, DogukanGun commented on src/components/side-effects/CommandInterface/index.tsx
> +  }
fixed

2023-06-13 09:31 UTC, ArnoClaude submitted a review, later dismissed
`Command + M` minimizes the browser window in Google Chrome on Mac, and `Control + M` doesn't do anything. So I don't know how to test this right now. Am I missing something?

2023-06-13 10:13 UTC, DogukanGun commented
> `Command + M` minimizes the browser window in Google Chrome on Mac, and `Control + M` doesn't do anything. So I don't know how to test this right now. Am I missing something?


Command+K works in Mac. Control + K works for windows

2023-06-13 10:20 UTC, ArnoClaude commented
> > `Command + M` minimizes the browser window in Google Chrome on Mac, and `Control + M` doesn't do anything. So I don't know how to test this right now. Am I missing something?
> 
> Command+K works in Mac. Control + K works for windows

Got it. The PR desc. still said M, so I changed it. Thanks for the info :)

2023-06-15 00:08 UTC, kigadye requested changes
Nice work, this is finally starting to come together! Only a few UI issues and it should be ready to get merged.

2023-06-15 00:08 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +    })
Think we don't need a catch here, router.push usually doesn't cause any errors

2023-06-15 00:08 UTC, kigadye commented on src/components/side-effects/Page/index.tsx
> +          })
same here, don't need the catch

2023-06-15 00:08 UTC, kigadye commented on src/pages/logout.tsx
I would do this extra confirmation step within the command interface, just like the additional step for details/ compare page instead of showing a modal because the modal doesn't really align with the rest of our UI

2023-06-15 00:08 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
Icons are too small
<img width="196" alt="Screenshot 2023-06-15 at 01 55 03" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/fac5c8a7-d7cf-4ee5-858f-5ba9946685d1">

2023-06-15 00:08 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
On details and compare pages, command interface is behind chart -> increase z-index
<img width="859" alt="Screenshot 2023-06-15 at 01 54 51" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/3718a9ae-95d8-4cd7-b7ac-d18bb0f00d80">

2023-06-15 00:08 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
Some project names break to 2 lines even though there is plenty of space
<img width="196" alt="Screenshot 2023-06-15 at 01 55 03" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/5cc2ad36-b900-4fc5-98ce-40fbd0affe7e">

2023-06-15 09:24 UTC, DogukanGun commented on src/components/side-effects/CommandInterface/index.tsx
> +    })
If i delete catch, eslint does not let me commit

2023-06-15 09:24 UTC, DogukanGun commented on src/components/side-effects/Page/index.tsx
> +          })
If i delete catch, eslint does not let me commit

2023-06-15 19:59 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +    })
just do `void router.push(path)`

2023-06-15 19:59 UTC, kigadye commented on src/components/side-effects/Page/index.tsx
> +          })
just do `void router.push(path)`

2023-06-15 20:17 UTC, kigadye requested changes
Fixed a few problems, introduced a few new ones 🤣 The following things should still be addressed (+ comments below):

- [ ] Use actual values for founder & company in email template
- [ ] Add confirmation step within command interface after selecting logout
- [ ] Go back to previous way of navigating to pages, don't trigger docs immediately on D because then I can't go to details any more
- [ ] Remove scrollbar on the right

2023-06-15 20:17 UTC, kigadye commented on src/components/side-effects/CommandInterface/DefaultRecommendationList.ts
> +    menuText: 'Home',
Rename home to trending projects

2023-06-15 20:17 UTC, kigadye commented on src/components/side-effects/CommandInterface/DefaultRecommendationList.ts
Use the same icons for the pages as used in the sidebar

2023-06-15 20:17 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +      className="fixed flex h-screen w-full items-start justify-center bg-black/50 shadow-lg"
this should fix the issue that the command interface appears under the chart on details & compare pages

2023-06-16 21:02 UTC, kigadye requested changes
Alright, looking much better. Only 2 things are still open from the last review:

- [ ] Go back to previous way of navigating to pages (don't trigger docs immediately on D because then I can't go to details any more)
- [x] Use actual values for founder & company in email template (currently using values from mock data)

2023-06-17 12:45 UTC, kigadye requested changes
Hm, now the navigation doesn't trigger immediately when I type D any more, but the extra step for details, compare, send mail and logout also don't work any more

2023-06-18 13:21 UTC, kigadye requested changes
one last thing - it should be possible to get to the second step of send mail, logout, details and compare using the enter key, not just the mouse

2023-06-18 15:40 UTC, kigadye approved these changes
Great work! I would say good to get merged for now, but there are still a few things that should be improved in a new PR:

- [ ] Split list into actions and navigation
- [ ] Move logout up into actions + change icon
- [ ] Only show send email on details page and automatically use current project
- [ ] Add navigation through items using up and down keys
- [ ] Fix shortcuts (not working for me because browser shortcuts override them, maybe look at how other apps do this)
- [ ] Document code

2023-06-18 16:21 UTC, DamianGrosz2 approved these changes

2023-06-18 16:21 UTC, merged