Front 31
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #19
Opened 2023-05-22 11:05 UTC by yinruo

I created the search bar, sort and filter button in filters.tsx and the token window in filters2.tsx.

2023-05-22 14:34 UTC, cnk1dev requested changes
Please add title and description according to coding guidelines so the PR can be properly reviewed

2023-05-23 12:16 UTC, pczern commented on .vscode/settings.json
> +{}
you can add `.vscode` in gitignore once it is removed

2023-05-23 12:17 UTC, pczern commented on src/pages/filters2.tsx
> +const MyComponent = () => {
The component name is wrong, I don't know what `MyComponent` is

2023-05-23 12:18 UTC, pczern commented on src/pages/filters2.tsx
> +  const cancelButtonStyle: React.CSSProperties = {
please create a CSS file and follow the CSS Rules as in the Guidelines with @apply keyword using tailwind CSS.
https://www.youtube.com/watch?v=mr15Xzb1Ook

do this by creating a component folder -> `mycomponent` put the component in `<my-component>/index.tsx` and css in `<my-component>/index.css`
whereever you put comments, make sure to distinguish between `pure`, `side-effect` and `page` components. `side-effect` is usually with `useEffect` and `page` is a component that should for a very very long time only be used on that specific page, because it is so specific

2023-05-23 12:23 UTC, pczern commented on src/pages/filters.tsx
> +  const openSortWindow = () => {
put functions and variables that are not dependent on state outside of component

2023-05-23 12:23 UTC, pczern commented on src/pages/filters.tsx
> +                <li key={option}>{option}</li>
we need ids

2023-05-23 12:23 UTC, pczern commented on src/pages/filters.tsx
> +                  onChange={() => handleOptionToggle('Newest')}
no arrow inline functions like this, generate a function and put into onChange before

2023-05-23 12:25 UTC, pczern commented on src/pages/filters.tsx
components should not be bigger than 120 lines at most, usually just 70 to 90 lines; split components up!

2023-05-23 12:28 UTC, pczern commented
@yinruo solve merge conflicts

2023-05-24 11:50 UTC, ArnoClaude commented
@yinruo Let me know if you need help solving the merge conflicts. Otherwise solve them, publish the PR, and tag me on Slack :)

2023-05-31 23:36 UTC, closed without merging