[FRONT-65] Google Authentication
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #24
Opened 2023-05-23 08:13 UTC by ArnoClaude

2023-05-23 08:15 UTC, ArnoClaude commented on src/components/pure/withAuth.tsx
> +      }, 500)
Comment by @cnk1dev initially: 
_We definitely shouldn't use a fixed timeout here but I also couldn't figure out how to do it instead, except with getServerSideProps, but I'm not sure if this is what we want. @pczern any input on this?_

2023-05-23 10:01 UTC, pczern requested changes

2023-05-24 15:17 UTC, pczern commented
this seems to work
```import { useUser, useSessionContext } from '@supabase/auth-helpers-react'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function withAuth<P extends JSX.IntrinsicAttributes>(
  WrappedComponent: React.ComponentType<P>
) {
  return (props: React.PropsWithChildren<P>) => {
    const { isLoading, error } = useSessionContext()
    const router = useRouter()
    const user = useUser()

    useEffect(() => {
      if (!isLoading && !user) void router.replace('/login')
    }, [isLoading])

    if (error) return <span style={{ color: 'white' }}>error</span>

    if (isLoading || !user) {
      return <span style={{ color: 'white' }}>loading</span>
    }

    // eslint-disable-next-line react/jsx-props-no-spreading
    return <WrappedComponent {...props} />
  }
}```

2023-05-25 10:10 UTC, pczern requested changes

2023-05-25 10:10 UTC, pczern commented on src/components/pure/withAuth.tsx
> +    }, [isLoading])
disable rule globally or in this line

2023-05-25 10:10 UTC, pczern commented on src/components/pure/withAuth.tsx
> +      return <span style={{ color: 'white' }}>loading</span>
Use some loading indicator

2023-05-25 10:10 UTC, pczern commented on src/components/pure/withAuth.tsx
> +    if (error) return <span style={{ color: 'white' }}>error</span>
use some error page or notification with redirect in useEffect

2023-05-25 12:25 UTC, pczern commented on src/components/pure/withAuth.tsx
it’s not pure component because of its side-effects place into components/side-effect

2023-05-25 13:07 UTC, ArnoClaude commented on src/pages/logout.tsx
> +  const signOut = useCallback(async () => {
@pczern I did it this way because you need the supabaseClient, which you get from useSupabaseClient, which you can only call inside the component.

2023-05-25 13:10 UTC, ArnoClaude commented on src/pages/login.tsx
> +  async function signInWithGoogle() {
@pczern Same reason as below; I wouldn't be able to use the `setError() `outside of the component.

2023-05-25 16:14 UTC, pczern commented on src/components/side-effects/withAuth.tsx
> +      if (!isLoading && !user) void router.replace('/login')
maybe add user as dependency, if the user is suddenly logged out, we want this to go to /login

2023-05-25 16:14 UTC, pczern commented on src/components/side-effects/withAuth.tsx
> +      if (!isLoading && !user) void router.replace('/login')
here is even something with subscription https://supabase.com/docs/guides/auth/quickstarts/react

2023-05-25 16:16 UTC, pczern commented on src/pages/login.tsx
> +  async function signInWithGoogle() {
will we then use `useCallback` on both or not? When should we use it?

2023-05-25 16:19 UTC, pczern commented on src/components/side-effects/withAuth.tsx
> +      if (!isLoading && !user) void router.replace('/login')
ok that's what `SessionContextProvider` uses under the hood

2023-05-25 16:21 UTC, pczern commented on src/pages/login.tsx
> +                signInWithGoogle().catch(() => setIsError(true))
nested inline function!!!!! remove this put another () => before your function above, so we can keep it out of the attributes; rename function to `handleSignIntWithGoogle` just for convention

2023-05-25 16:22 UTC, pczern commented on src/pages/login.tsx
> +  async function signInWithGoogle() {
we don't do `useCallback` on function which are not computively expensive

2023-05-25 16:22 UTC, pczern commented on src/pages/logout.tsx
> +  const signOut = useCallback(async () => {
we are not using `useCallback` for non expensive function calls

2023-05-26 11:19 UTC, ArnoClaude commented
@pczern I removed `useCallbacks` for signIn and signOut

2023-05-26 11:33 UTC, pczern requested changes

2023-05-26 11:33 UTC, pczern commented on src/pages/logout.tsx
> +  }, [user, router, signOut])
remove signOut and router as Dependency

2023-05-26 15:42 UTC, pczern approved these changes

2023-05-26 16:17 UTC, cnk1dev requested changes
Looks good, a few things still need to be looked at though

2023-05-26 16:17 UTC, cnk1dev commented on src/pages/error.tsx
> +        <p>Something went wrong. Tough luck, you sucker!</p>
Let's phrase this a bit more politely 🤣

2023-05-26 16:17 UTC, cnk1dev commented on src/pages/login.tsx
> +            <div className="mb-4 text-36 font-semibold text-gray-100">Welcome to TruffleAI</div>
```suggestion
            <div className="mb-4 text-36 font-semibold text-gray-100">Something went wrong</div>
```

2023-05-26 16:17 UTC, cnk1dev commented on src/pages/login.tsx
> +      <main className={`${inter.className} flex min-h-screen flex-col`}>
Move error to separate component, parameterize title & message and use the same in error page

2023-05-26 16:17 UTC, cnk1dev commented on src/pages/login.tsx
> +            <p>You are already logged in.</p>
Redirect to / instead of showing you are logged in

2023-05-26 16:17 UTC, cnk1dev commented on src/pages/logout.tsx
Logout doesn't work (at least for me - cookie is not removed)

2023-05-26 18:21 UTC, pczern commented on src/pages/logout.tsx
should be fixed @cnk1dev

2023-05-27 15:46 UTC, cnk1dev approved these changes
Loading should be moved to a normal component instead of page but will be done in later PR

2023-05-27 15:47 UTC, merged