[Meta 50] Add SASS support
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #25
Opened 2023-05-23 19:05 UTC by pczern

### Description
Add support for SASS for writing styles

### Reasons
[Tailwind configs](https://tailwindcss.com/docs/using-with-preprocessors) suggest to use PostCSS for better speed. Next.js seems not to allow the `parser` and `syntax` property, but only the `plugins` property in `postcss.config.js`, therefore [sugarss](https://github.com/postcss/sugarss) can not be used. Next.js comes with SASS support once `sass` package is installed.

### How I implemented
Installed the `sass` package, added an example with the BEM syntax

### Additional
* Curly braces are not needed to write CSS, why write more code if less is enough?
* See https://github.com/postcss/sugarss/issues/101
* Follow https://github.com/vercel/next.js/discussions/23255
* This VScode extension is available https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented
* **Prettier doesn't support SASS!** we have to make sure styles are formatted

2023-05-25 06:49 UTC, DamianGrosz2 approved these changes
Looks good, but lets try to use mostly Tailwind, otherwise we get complex/weird stylesheets in different places.

2023-05-25 18:29 UTC, pczern commented
@ArnoClaude , @cnk1dev

2023-05-25 19:11 UTC, cnk1dev requested changes

2023-05-25 19:11 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
Actually we don't really need BEM syntax for CSS modules as class names are locally scoped (I thought that's the whole point of it)

2023-05-25 19:11 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
I would use styles for the name of the import as it's the usual convention for CSS modules (at least in my experience)

2023-05-25 19:11 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
I would name CSS modules files [component-name].module.sass

2023-05-25 20:53 UTC, pczern commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
but css is shorter, this is pro level

2023-05-26 09:01 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
nah, don't agree, it's additionally confusing because it's sass 🙃

2023-05-26 09:01 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
@pczern why not?

2023-05-26 17:40 UTC, pczern commented on src/components/pure/Sidebar/Box/index.module.sass
okay this is the only change I can live with, not that I agree; For TSX files it's possible to not have to write out `index.tsx` for imports, but for the sass file it will be required. But in general I prefer a `index.tsx` file in a folder than the same name as the folder

2023-05-26 17:43 UTC, pczern commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
As this will be used multiple times (up to 30 times) in each component, and `css` just uses two letters; it is much faster for typing, easy recognizable and doesn't clutter component files

2023-05-26 17:44 UTC, pczern commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
some people use it rather than `styles`, I didn't invent this

2023-05-26 17:45 UTC, pczern commented on src/components/pure/Sidebar/Box/index.module.sass
The point of BEM syntax is not local scoping

2023-05-26 21:16 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
atm we don't have folders for every component though

2023-05-26 21:17 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.tsx
> +import css from './index.module.sass'
ok let's leave it at that then

2023-05-26 21:18 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
The point of BEM syntax is preventing css class name conflicts and the point of CSS modules is local scoping which prevents class name conflicts

2023-05-27 19:16 UTC, pczern commented on src/components/pure/Sidebar/Box/index.module.sass
well I can compromise, but this means we shall have no index files?

2023-05-27 20:44 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
yes

2023-05-28 14:17 UTC, DogukanGun approved these changes

2023-05-28 15:16 UTC, pczern commented on src/components/pure/Sidebar/Box/index.module.sass
no, the [getbem](https://getbem.com/introduction/) website states as benefit explicitly modularity, reusability and structure and doesn't mention any css class name conflicts, even though this might have been a benefit before the 2010s

2023-05-28 15:27 UTC, pczern commented on src/components/pure/Sidebar/Box/index.module.sass
The more I google about it I find a lot of advanced devs using it. It seems to be followed by very consistent design oriented people, see for example the slides here https://www.mattzeunert.com/slides/bem-ldn-ajax.pdf

2023-05-28 19:48 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/index.module.sass
ok let's use it then, I just think it's ugly and not really necessary in 20 lines sass files but if you're coming with articles and arguments I'll fold

2023-05-28 19:49 UTC, cnk1dev approved these changes

2023-05-29 10:41 UTC, merged