initial commit for FRONT-74
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #27
Opened 2023-05-25 22:34 UTC by DamianGrosz2

###Description of Issue
The placement of the buttons above the chart has been improved to enhance the overall layout. 
The date format has been updated to "Month Year" for improved readability. 
Lastly, the design of the chart has been updated.

###How I implemented
To achieve these improvements, the following changes were made:

Adjusted the positioning of the buttons to be placed above the chart.
Updated the date format.
Made design updates to enhance the visual aesthetics.

###Other

Please review and merge this pull request.

2023-05-26 15:47 UTC, pczern approved these changes
it's an improvement to what we have, so direct approval. Work in progress when it comes to number of lines per component, and some redundant type that can be adjusted later though

2023-05-26 16:29 UTC, cnk1dev requested changes
<img width="174" alt="Screenshot 2023-05-26 at 18 26 54" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/34f794ed-1f74-49a8-9c07-d3b34d07d626">

Please improve the chart tooltip (if possible):
- reduce font size to match rest of page
- remove "value: "
- add border-radius
- use same border-color as buttons

2023-05-26 18:32 UTC, DamianGrosz2 commented
> it's an improvement to what we have, so direct approval. Work in progress when it comes to number of lines per component, and some redundant type that can be adjusted later though

Yes but also this depends still on the backend data so when we have that the types will change

2023-05-26 20:16 UTC, cnk1dev requested changes
<img width="205" alt="Screenshot 2023-05-26 at 22 11 13" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/b20caa1d-4f9c-4b67-bf74-b60b7087a13d">


Better but still luft nach oben 🥸
- Make the value (not the date) in the tooltip bold and add a few pixels of spacing above it
- Make the vertical indicator line which appears on hover grey
- Reduce font size of purple "value" at the bottom

Sorry for being so stingy but Viet is very focused on design so let's try to make it perfect

2023-05-26 20:16 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +              stroke="#858699"
Please use Tailwind colors instead of hex values

2023-05-27 14:28 UTC, cnk1dev approved these changes
Still uses hard-coded hex values in Chart.tsx, I'll approve for now and change that later myself though

2023-05-27 14:48 UTC, merged