FRONT-70
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #28
Opened 2023-05-26 10:25 UTC by mohammad-akkad

2023-05-29 11:02 UTC, DamianGrosz2 approved these changes

2023-05-29 13:53 UTC, cnk1dev requested changes
Please have a look at my comments below. Also:
- [x] Make TruffleAI logo/ sidebar title bigger & bolder
- [ ] Add link to / on logo, trending projects & all bookmarks

2023-05-29 13:53 UTC, cnk1dev commented on package.json
> +    "react-beautiful-dnd": "^13.1.1",
Remove `react-beautiful-dnd` if it's not being used yet

2023-05-29 13:53 UTC, cnk1dev commented on src/components/pure/Sidebar/Section/index.tsx
> +    <h1 className="px-7 py-2.5 text-12 font-medium uppercase text-gray-400">{title}</h1>
Use h3 or p here + make section title smaller like in Figma

2023-05-29 13:53 UTC, cnk1dev commented on src/components/side-effects/NavSidebar.tsx
> +        text: 'microsfot / playwright',
```suggestion
        text: 'microsoft / playwright',
```

2023-05-29 13:53 UTC, cnk1dev commented on src/components/pure/Sidebar/Section/Item.tsx
- [ ] Change icon for project to filled circle like in design
- [ ] Fix glitch on hover when title is too long
- [ ] Disable editing & removing actions for now (keep the icons but remove click handlers)
- [ ] Link projects to /details/<id>
- [ ] Link folders to /compare/<category>
- [ ] Fix cut off text at the bottom:
<img width="143" alt="Screenshot 2023-05-29 at 15 45 35" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/c4fea336-012a-43f7-80e1-663f3c5740ca">

2023-05-29 14:03 UTC, cnk1dev commented on src/components/side-effects/NavSidebar.tsx
> +        <Sidebar.Section title={section.title}>
Add key to section

2023-05-29 14:29 UTC, DamianGrosz2 commented on package.json
> +    "react-beautiful-dnd": "^13.1.1",
done

2023-05-29 14:34 UTC, DamianGrosz2 commented on src/components/side-effects/NavSidebar.tsx
> +        <Sidebar.Section title={section.title}>
done

2023-05-29 14:41 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Section/index.tsx
> +    <h1 className="px-7 py-2.5 text-12 font-medium uppercase text-gray-400">{title}</h1>
done

2023-05-29 17:01 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Section/Item.tsx
done

2023-05-30 08:39 UTC, pczern requested changes

2023-05-30 08:39 UTC, pczern commented on package.json
> +    "@types/react-beautiful-dnd": "^13.1.4",
wrong location

2023-05-30 12:14 UTC, DamianGrosz2 commented on src/components/side-effects/NavSidebar.tsx
> +    alert(`Saved ${newText}`)
why, this is just for demo purposes

2023-05-30 12:16 UTC, DamianGrosz2 commented on src/components/side-effects/NavSidebar.tsx
> +    // setSections(
but the functionality would work like this, once the data is there

2023-05-30 12:16 UTC, DamianGrosz2 commented on src/components/side-effects/NavSidebar.tsx
> +    // setSections(
but the functionality would work like this, once the data is there

2023-05-30 12:19 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Section/Item.tsx
> +    // TODO
fixed

2023-05-30 12:19 UTC, DamianGrosz2 commented on package.json
> +    "@types/react-beautiful-dnd": "^13.1.4",
fixed

2023-05-30 12:20 UTC, DamianGrosz2 commented on src/components/side-effects/NavSidebar.tsx
> +  const initialSections = [
done

2023-05-31 10:52 UTC, cnk1dev commented on src/components/side-effects/NavSidebar.tsx
> +    // setSections(
removed

2023-05-31 10:52 UTC, cnk1dev commented on src/components/side-effects/NavSidebar.tsx
> +    // setSections(
removed

2023-05-31 10:58 UTC, cnk1dev approved these changes

2023-05-31 15:02 UTC, pczern requested changes

2023-05-31 18:23 UTC, cnk1dev commented on package-lock.json
regenerated `package-lock.json`

2023-05-31 18:25 UTC, pczern approved these changes

2023-05-31 18:25 UTC, merged