[FRONT-73] Update UI to match current design
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #30
Opened 2023-05-26 15:13 UTC by ArnoClaude

### Description of Issue
[Linear Issue](https://linear.app/la-famiglia-project/issue/FRONT-73/create-edit-displayed-column)

- A modal has been added to edit columns.
- A new topbar has been implemented with several buttons; however, these buttons do not currently have associated functionality (only edit columns)
- A filter bar has been introduced, but it currently does not include any filters.
- The 'Owner' and 'Name' columns have been merged for better clarity.
- A new column for logos has been introduced, (actual images missing)
- Rows are now wrapped in a Link, leading to a detailed page.
- Styling modifications have been made across the platform, including:

1. Colored values based on thresholds.
2. Adjusted tag colors.
3. Reformatted header styles.
4. Tweaked styles in various components.
5. Adjusted font weights, capitalization, icon colors, and the border radius of rows.

### How I implemented
I used the [Tailwind UI Dropdown](https://tailwindui.com/components/application-ui/elements/dropdowns) component

### Other
"@headlessui/react" is used for the Popup

2023-05-27 14:43 UTC, cnk1dev requested changes
Great work, a few small things still need to be fixed though.

2023-05-27 14:43 UTC, cnk1dev commented on src/components/pure/RepositoryTable/index.tsx
> +                      typeof column.header === 'function' ? column.header() : column.header
Build fails because of this. Line 220 was split up into 2 by prettier, that's why @ts-ignore doesn't apply for 221 any more and causes the error. Regardless of that, it should be fixed, not ignored: column.header() requires an argument of type `HeaderContext<Repository, number>`

2023-05-27 14:43 UTC, cnk1dev commented on src/components/pure/RepositoryTable/index.tsx
>  const browseListColumns = [
Move `browseListColumns` into a separate `columns.tsx` file next to `index.tsx` and import it to reduce the size of the huge table component

2023-05-27 15:46 UTC, DamianGrosz2 commented on src/components/pure/RepositoryTable/index.tsx
> +                      typeof column.header === 'function' ? column.header() : column.header
I dont really understand what argument that could be

2023-05-27 16:00 UTC, DamianGrosz2 commented on src/components/pure/RepositoryTable/index.tsx
>  const browseListColumns = [
ok done

2023-05-27 20:38 UTC, cnk1dev approved these changes

2023-05-28 07:55 UTC, DamianGrosz2 approved these changes

2023-05-28 11:36 UTC, pczern requested changes

2023-05-28 11:36 UTC, pczern commented on package.json
> +    "@headlessui/react": "^1.7.14",
add why packages were added in PR description

2023-05-28 11:36 UTC, pczern commented on src/components/page/details/Chart.tsx
>    const dataTypes = useMemo(() => data.map((d) => d.name), [data])
do not useMemo without measuring using withProfiler

2023-05-28 11:36 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                  key={nanoid()}
we don't need nanoid(); this id is not consistent!!!! Component gets rerendered more often

2023-05-28 11:36 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                  key={nanoid()}
same here

2023-05-28 11:36 UTC, pczern commented on src/components/page/details/ProjectInformation.tsx
> +  image: string // TODO: change type
`@TODO` capital case

2023-05-28 11:36 UTC, pczern commented on src/components/page/repositoryTable/Table.tsx
rename to RepositoryTable.tsx

2023-05-28 11:36 UTC, pczern commented on src/components/page/repositoryTable/TopBar.tsx
> +        <Button
put an array with attributes above TopBar component and render all three, we want to keep components small

2023-05-28 11:36 UTC, pczern commented on src/components/page/repositoryTable/columns.tsx
> +      // <img
remove comment

2023-05-28 11:36 UTC, pczern commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  greenValue,
As only one color is chosen use one prop, you can provide defaults via an enum

2023-05-28 11:36 UTC, pczern commented on src/data/repositoriesMock.ts
> +    logo: '',
Make your code work with logo undefined?

2023-05-28 14:15 UTC, DogukanGun requested changes

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/details/Chart.tsx
>    useEffect(() => {
Please add a description for this useEffect

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/details/Chart.tsx
>                {dataTypes.map((item) => (
Please check dataTypes is empty or not. If the list empty please show a message for the user.

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/details/ProjectInformation.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars
Please do not disable anything.

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/details/ProjectInformation.tsx
>  const ProjectInformation = ({ image, name, eli5, tags }: ProjectInformationProps) => (
You should define type for the all values in props.

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/details/ProjectInformation.tsx
>          {tags.map((text) => (
Please check tags is empty or not. If the list empty please show a message for the user.

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/repositoryTable/Filterbar.tsx
> +const nullFunc = () => null
Could you explain why you created this function ?

2023-05-28 14:15 UTC, DogukanGun commented on src/components/page/repositoryTable/columns.tsx
> +        paddingOn={false}
I think that you dont need use brackets for constant values. I mean you coudl write "2000" instead of {2000}. Could you check this?

2023-05-28 14:16 UTC, DogukanGun requested changes
Please check the feedbacks from me and there are some not answered feedbacks.

2023-05-28 15:03 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
>    const dataTypes = useMemo(() => data.map((d) => d.name), [data])
Please, when providing feedback also include possible suggestions :)

2023-05-28 15:16 UTC, DamianGrosz2 commented on src/components/page/repositoryTable/TopBar.tsx
> +        <Button
I disagree. this makes the code less readable, also it's just 3 buttons

2023-05-28 15:24 UTC, DamianGrosz2 commented on src/components/page/repositoryTable/Table.tsx
Actually we have already a component called like that

2023-05-28 15:28 UTC, DamianGrosz2 commented on src/components/page/details/ProjectInformation.tsx
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars, no-unused-vars
Its a todo, as long as we dont have images

2023-05-28 15:29 UTC, DamianGrosz2 commented on src/components/page/details/ProjectInformation.tsx
>  const ProjectInformation = ({ image, name, eli5, tags }: ProjectInformationProps) => (
They are above?

2023-05-28 15:31 UTC, DamianGrosz2 commented on src/components/page/repositoryTable/Filterbar.tsx
> +const nullFunc = () => null
Yes thats just as a dummy whilst the actual component is being worked on

2023-05-28 15:35 UTC, DamianGrosz2 commented on src/components/page/repositoryTable/columns.tsx
> +        paddingOn={false}
No doesnt work

2023-05-28 19:09 UTC, cnk1dev commented on src/components/page/repositoryTable/TopBar.tsx
> +        <Button
agree with @DamianGrosz2, also component is only 124 lines so it technically conforms to the max 140 line "rule"

2023-05-28 19:09 UTC, cnk1dev commented on src/components/page/repositoryTable/Table.tsx
imo we should also consider renaming a few other components but would do that in another PR

2023-05-28 19:10 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
>    const dataTypes = useMemo(() => data.map((d) => d.name), [data])
removed useMemo

2023-05-28 19:10 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +                  key={nanoid()}
my bad, fixed

2023-05-28 19:10 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +                  key={nanoid()}
fixed

2023-05-28 19:12 UTC, cnk1dev commented on src/data/repositoriesMock.ts
> +    logo: '',
fixed

2023-05-28 19:13 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
>                {dataTypes.map((item) => (
now displaying a fallback message for the entire chart if there's no data

2023-05-29 10:54 UTC, pczern requested changes

2023-05-29 10:54 UTC, pczern commented on src/components/page/repositoryTable/TopBar.tsx
> +        <Button
the limit is too high

2023-05-29 10:54 UTC, pczern commented on src/components/page/details/ProjectInformation.tsx
> +  image: string // TODO: change type
`@`

2023-05-29 10:54 UTC, pczern commented on src/components/page/repositoryTable/columns.tsx
> +      // <img
still there

2023-05-29 10:54 UTC, pczern commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  greenValue,
why are all requests marked resolved?

2023-05-29 11:33 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  greenValue,
I had done them and resolved the. But didn't push bc I had to go then Clemens did them.

2023-05-29 12:02 UTC, pczern requested changes

2023-05-29 12:02 UTC, pczern commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  const valueAsNumber = Number(value)
what? why is value not Number prop? What is value?

2023-05-29 13:35 UTC, cnk1dev commented on src/components/page/repositoryTable/TopBar.tsx
> +        <Button
ok I'll address that in a later PR with some general refactoring though

2023-05-29 13:36 UTC, cnk1dev commented on src/components/page/repositoryTable/columns.tsx
> +      // <img
gone now

2023-05-29 13:36 UTC, cnk1dev commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  const valueAsNumber = Number(value)
fixed

2023-05-29 15:29 UTC, pczern approved these changes

2023-05-29 16:08 UTC, DamianGrosz2 commented on src/components/page/details/ProjectInformation.tsx
>          {tags.map((text) => (
Done

2023-05-29 16:09 UTC, merged