[META-51] Connect frontend to backend
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #31
Opened 2023-05-26 16:58 UTC by cnk1dev

2023-05-29 15:02 UTC, pczern requested changes

2023-05-29 15:02 UTC, pczern commented on src/components/page/details/ProjectInformation.tsx
> +  image: undefined
?

2023-05-29 15:02 UTC, pczern commented on src/components/page/details/ProjectInformation.tsx
> +        {/* TODO: Replace with actual image */}
`@TODO`

2023-05-29 15:02 UTC, pczern commented on src/components/page/details/ProjectInformation.tsx
> +  image?: string
why optional

2023-05-29 15:02 UTC, pczern commented on package.json
> +    "dev": "next dev -p 3002",
change back to 3000

2023-05-29 16:31 UTC, cnk1dev commented on src/components/pure/Loading.tsx
> +  message: undefined
fixed

2023-05-29 16:32 UTC, cnk1dev commented on src/pages/details/[id].tsx
> +      <Details id={(typeof id === 'string' ? id : id?.join('')) || ''} />
`const id: string | string[] | undefined`

2023-05-29 16:33 UTC, cnk1dev commented on src/pages/_app.tsx
> +        Authorization: document.cookie
manually sends the supabase cookie as authorization header on every request made with the urql client

2023-05-29 16:33 UTC, cnk1dev commented on src/components/side-effects/LeftSidebar.tsx
renamed back to NavSidebar

2023-05-29 16:34 UTC, cnk1dev commented on src/components/pure/Error.tsx
> +  title?: string
I added default props so you can just use the error component without supplying a title and message, it's likely gonna be the same standard message in most cases

2023-05-29 16:34 UTC, cnk1dev commented on src/components/page/details/ProjectInformation.tsx
> +  image: undefined
fixed

2023-05-29 16:35 UTC, cnk1dev commented on src/components/page/details/ProjectInformation.tsx
> +        {/* TODO: Replace with actual image */}
fixed all TODOs

2023-05-29 16:36 UTC, cnk1dev commented on src/components/page/details/ProjectInformation.tsx
> +  image?: string
because some projects might not have an image_url, in that case we'll just display a placeholder image/ grey background

2023-05-29 16:37 UTC, cnk1dev commented on package.json
> +    "dev": "next dev -p 3002",
done

2023-05-29 20:41 UTC, DamianGrosz2 approved these changes

2023-05-29 20:41 UTC, DamianGrosz2 commented
Looks good

2023-05-29 21:39 UTC, cnk1dev commented
Need to run codegen again before merging to update types but backend is down atm

2023-05-30 09:11 UTC, pczern commented on src/components/pure/ProjectsTable/index.tsx
Github has projects and repositories; is this a Repository Table or a Project Table?

2023-05-30 09:13 UTC, pczern commented on src/pages/details/[id].tsx
> +      <Details id={(typeof id === 'string' ? id : id?.join('')) || ''} />
how can it be ever undefined?

2023-05-30 10:36 UTC, cnk1dev commented on src/pages/details/[id].tsx
> +      <Details id={(typeof id === 'string' ? id : id?.join('')) || ''} />
idk but it comes straight from `useRouter()` so what else should I do?

<img width="230" alt="Screenshot 2023-05-30 at 12 36 24" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/078f9e6a-13c1-4b5e-8afd-23eb5bb0263d">

2023-05-30 10:40 UTC, cnk1dev commented on src/components/pure/ProjectsTable/index.tsx
Imo we should use the term project and not repository in truffle, even if all projects are repositories atm. Project doesn't mean GitHub project though, but rather product or company. We might add other data sources in the future, so we should keep the terminology more general.

2023-06-01 09:17 UTC, pczern commented on codegen.config.ts
> +  documents: './src/queries/**/*.graphql',
let's do `graphql/queries`

2023-06-01 09:18 UTC, pczern commented on src/components/page/details/Chart.tsx
> +export type ChartProps = {
I think an export is not needed as React has very good Utility functions to type components

2023-06-01 09:18 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                  key={dataset.name}
i've already given up on `id`s

2023-06-01 09:19 UTC, pczern commented on src/components/page/details/CustomTooltip.tsx
> +        <p className="mt-2 font-bold">{formatNumber(parseFloat(payload[0].value as string))}</p>
this is a Tooltip component, how does it know about an array payload?
Design components without inherent design in mind. `body`,`title`

2023-06-01 09:28 UTC, pczern commented on src/components/pure/Loading.tsx
> +    <div />
what is this `<div />`

2023-06-01 09:29 UTC, pczern commented on codegen.config.ts
> +  documents: './src/queries/**/*.graphql',
and for codgen `graphql/generated`

2023-06-02 07:41 UTC, cnk1dev commented on codegen.config.ts
> +  documents: './src/queries/**/*.graphql',
done

2023-06-02 07:41 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +export type ChartProps = {
used `React.ComponentProps` instead

2023-06-02 07:52 UTC, cnk1dev commented on src/components/pure/Loading.tsx
> +    <div />
for alignment

2023-06-02 07:56 UTC, cnk1dev commented on src/components/page/details/CustomTooltip.tsx
> +        <p className="mt-2 font-bold">{formatNumber(parseFloat(payload[0].value as string))}</p>
recharts requires a custom Tooltip component to be passed to its options, this component is only being used for that. I could wrap it in another component and pass down the props but don't see any advantage in doing that

2023-06-02 08:00 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +                  key={dataset.name}
added project id to dataset and used as key

2023-06-02 08:02 UTC, merged