[Front-78] Add Time Selector to details page
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #35
Opened 2023-05-29 15:02 UTC by WrappedSuperClass

Time Selector: 

Upon clicking "Edit Timeframe", there should be a dropdown with "Today/This week/This month" options. 

I reused the Modal.tsx and added it to the code using the three requried buttons. 
To fix the modal under the button while scrolling up und down i changed the css class from fixed to absolute.

2023-05-30 07:55 UTC, pczern requested changes

2023-05-30 07:55 UTC, pczern commented on src/pages/details.tsx
> +                  onClick={() => handleClick}
handleClick

2023-05-30 07:55 UTC, pczern commented on src/pages/details.tsx
> +                  onClick={() => handleClick}
handleClick

2023-05-31 10:16 UTC, cnk1dev requested changes

2023-05-31 10:16 UTC, cnk1dev commented on src/pages/details.tsx
>    // TODO: Implement click handler
```suggestion
  // @TODO Implement click handler
```

2023-05-31 10:21 UTC, cnk1dev commented on src/pages/details.tsx
> +                  onClick={() => handleClick}
fixed

2023-05-31 10:21 UTC, cnk1dev commented on src/pages/details.tsx
>    // TODO: Implement click handler
fixed

2023-05-31 10:23 UTC, cnk1dev approved these changes

2023-05-31 15:03 UTC, pczern approved these changes

2023-05-31 18:10 UTC, merged