[Front-90]: Profile Modal for Log out and Settings
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #41
Opened 2023-06-04 18:38 UTC by WrappedSuperClass

###Description of issue
Somewhere in the Sidebar, eg by clicking on the profile pic, you should get a dropdown with the options to Log Out or Settings, which will then later (not part of this task) lead to the Settings page.

###How I implemented
I used the Menu commponent and added a divider 
Fixed the path of the button of the sidebar
###Other

2023-06-05 14:51 UTC, ArnoClaude requested changes
Great job, Lukas! @WrappedSuperClass I left some minor improvement suggestions :)

2023-06-05 14:51 UTC, ArnoClaude commented on src/components/pure/Sidebar/index.tsx
> +            <div className="" />
What is this empty div for? Also, if you don't have any class names, you can just omit the className attribute :)

2023-06-05 14:51 UTC, ArnoClaude commented on src/components/pure/Sidebar/index.tsx
> +              <AiFillSmile color="#858699" />
Please use our brand colors from the `tailwind.config.js`

2023-06-05 14:51 UTC, ArnoClaude commented on src/components/pure/Sidebar/index.tsx
> +            <Menu.Items className="absolute right-0 z-10 mt-2 w-44 origin-top-right rounded-md bg-gray-700 shadow-lg ring-1 focus:outline-none">
I would not make the width fixed. Just let the dropdown take up as much width as it needs :)

![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/3fd537f1-4e91-47fd-b59b-191fa4a36d97)

2023-06-08 17:52 UTC, WrappedSuperClass commented on src/components/pure/Sidebar/index.tsx
> +            <div className="" />
i don't know, tbh :)

I deleted it

2023-06-08 17:52 UTC, WrappedSuperClass commented on src/components/pure/Sidebar/index.tsx
> +              <AiFillSmile color="#858699" />
fixed!

2023-06-08 17:52 UTC, WrappedSuperClass commented on src/components/pure/Sidebar/index.tsx
> +            <Menu.Items className="absolute right-0 z-10 mt-2 w-44 origin-top-right rounded-md bg-gray-700 shadow-lg ring-1 focus:outline-none">
fixed!

2023-06-08 21:59 UTC, kigadye approved these changes

2023-06-08 21:59 UTC, merged