[FRONT-102] Change Hex Values to Tailwind Classes
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #43
Opened 2023-06-06 10:53 UTC by ArnoClaude

## Description of Issue
[Linear Issue](https://linear.app/la-famiglia-project/issue/FRONT-102/change-hex-colors-to-tailwind-names)
## How I implemented
## Other
A neat trick to find all hex code occurrences in WebStorm:
`Cmd + Shift + F` to open global search, then tick the `RegEx` search, then type in the RegEx for hex values (`#[0-9a-fA-F]{6}`):
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/924ae810-8cb6-40d3-89e2-cf3d906724ba)

Additionally, you can filter by file type. In my case only .tsx files were interesting:
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/16efb121-fa4c-4884-9079-dc59a911311e)

2023-06-06 18:58 UTC, cnk1dev requested changes

2023-06-06 18:58 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="gray" />
I think this is the wrong gray, should be gray-800

2023-06-07 13:27 UTC, ArnoClaude commented on src/components/page/details/Chart.tsx
> +              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="gray" />
The problem is that the stroke attribute cannot take Tailwind classes, as it is a JS object and not JSX. So we either keep `gray` or use the hex code of our `gray-800` directly. What do you suggest? @cnk1dev

2023-06-07 13:43 UTC, cnk1dev commented on src/components/page/details/Chart.tsx
> +              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="gray" />
[This should work](https://tailwindcss.com/docs/configuration#referencing-in-java-script)

2023-06-08 09:25 UTC, DamianGrosz2 approved these changes

2023-06-08 10:04 UTC, pczern approved these changes

2023-06-08 10:32 UTC, merged