[FRONT-89] add project modal
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #47
Opened 2023-06-06 23:29 UTC by mohammad-akkad

### Description
Added add project Modal

### How I implemented
I added a pure component which is the Input modal with a dynamic header

![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/51421553/5ed3b082-424c-43c9-b06d-36e0d1b0a44f)

2023-06-07 13:18 UTC, ArnoClaude requested changes
Looks good. I left some small comments :)

2023-06-07 13:18 UTC, ArnoClaude commented on src/components/page/overview/TopBar.tsx
> +            text="Add Project"
I know the Figma mockups look like this, but I find it confusing to have this text be the same as the button that opens the modal; Can you remove the "+" icon and rename "Add Project" to "Save", please?

2023-06-07 13:18 UTC, ArnoClaude commented on src/components/page/overview/TopBar.tsx
> +          className="mb-4 w-full rounded-lg bg-gray-200 px-3 py-2"
Can you make the text more readable?
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/5c8315a4-836f-4838-bf18-d886d1fff485)

2023-06-07 13:18 UTC, ArnoClaude commented on src/components/pure/InputModal.tsx
> +            <Button onClick={onClose} variant="onlyIconNoBorderNoBG" Icon={AiOutlineClose} />
Can you give the x closing icon a hover effect? And, if you close the modal, delete the input, such that after re-opening it, the input field is empty again.

2023-06-08 21:53 UTC, mohammad-akkad commented on src/components/pure/InputModal.tsx
> +            <Button onClick={onClose} variant="onlyIconNoBorderNoBG" Icon={AiOutlineClose} />
it already have hover effect I think like this
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/51421553/a9c82396-e7f0-4de6-8dcb-f77d0e017b23)

2023-06-10 07:24 UTC, ArnoClaude requested changes

2023-06-10 07:24 UTC, ArnoClaude commented on src/components/page/overview/TopBar.tsx
> +            Icon={AiOutlinePlus}
Icon not needed. Just have to button say "Save".

2023-06-10 07:24 UTC, ArnoClaude commented on src/components/page/overview/TopBar.tsx
> +        <input
@kigadye How "smart" do we want this input to be? The Figma mockups suggest that, because it will always be a GitHub repo, there is a greyed-out "github.com/", and the user text input appears after it.
@mohammad-akkad Please add an error message in case the repo is not found.

![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/e5bc8128-e2dc-4d7d-a839-d617f4b26ebb)

2023-06-11 01:31 UTC, kigadye commented on src/components/page/overview/TopBar.tsx
> +        <input
@ArnoClaude let's just keep it simple and use the GitHub URL from Figma as placeholder to indicate to the user that they need to enter the URL of a repo, but not limit the user to what they paste in there, if it's invalid the backend will catch that

2023-06-17 15:25 UTC, kigadye approved these changes

2023-06-17 19:21 UTC, ArnoClaude approved these changes

2023-06-17 19:21 UTC, merged