[FRONT-99] Show multiple lines in chart
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #49
Opened 2023-06-08 12:14 UTC by DamianGrosz2

2023-06-09 10:43 UTC, ArnoClaude commented
Looks really good, great work, Damian! The UX could definitely need some improvements, especially when there are a lot of projects/graphs in the figure.
Some suggestions:
- Sort the names of the project below the figure by their current (most recent) value. So, in this example, `gorilla` is first, then `chinese-poetry` would come next, because its line/current value is second
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/f41ecc50-a58a-47a2-937b-c65e1386682c)
- When hovering over a graph, have a tooltip that shows the name of the repository you are hovering over (as well as the value on the point you are hovering over)

2023-06-09 10:43 UTC, ArnoClaude requested changes

2023-06-09 10:43 UTC, ArnoClaude commented on src/components/page/details/Chart.tsx
> +  // const [isModalOpen, setIsModalOpen] = useState(false)
Remove comments if not needed now

2023-06-10 14:57 UTC, DamianGrosz2 commented
> * Sort the names of the project below the figure by their current (most recent) value. So, in this example, `gorilla` is first, then `chinese-poetry` would come next, because its line/current value is second



> Looks really good, great work, Damian! The UX could definitely need some improvements, especially when there are a lot of projects/graphs in the figure. Some suggestions:
> 
> * Sort the names of the project below the figure by their current (most recent) value. So, in this example, `gorilla` is first, then `chinese-poetry` would come next, because its line/current value is second
>   ![image](https://user-images.githubusercontent.com/61106168/244670509-f41ecc50-a58a-47a2-937b-c65e1386682c.png)
> * When hovering over a graph, have a tooltip that shows the name of the repository you are hovering over (as well as the value on the point you are hovering over)



> Looks really good, great work, Damian! The UX could definitely need some improvements, especially when there are a lot of projects/graphs in the figure. Some suggestions:
> 
> * Sort the names of the project below the figure by their current (most recent) value. So, in this example, `gorilla` is first, then `chinese-poetry` would come next, because its line/current value is second
>   ![image](https://user-images.githubusercontent.com/61106168/244670509-f41ecc50-a58a-47a2-937b-c65e1386682c.png)
> * When hovering over a graph, have a tooltip that shows the name of the repository you are hovering over (as well as the value on the point you are hovering over)

1. Done
2. Recharts doesn't provide this kind of tooltip for only one line, but rather all lines on a given x value.

2023-06-11 10:13 UTC, ArnoClaude approved these changes
Looks good to me now :)

2023-06-11 12:39 UTC, pczern commented on src/components/page/details/Chart.tsx
> +colorValues.forEach((value) => {
use `map`

2023-06-11 12:42 UTC, pczern requested changes

2023-06-11 12:42 UTC, pczern commented on src/components/page/details/Chart.tsx
> +singleColors.forEach((colorName) => {
use `concat`

2023-06-11 12:42 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                      onClick={() => handleTimeframeChange(option.value)}
handlers are usually already wrapped, change this to onClick={handleTimeframeChange...

2023-06-12 10:48 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +colorValues.forEach((value) => {
done

2023-06-12 10:48 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +singleColors.forEach((colorName) => {
done

2023-06-12 10:55 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +                      onClick={() => handleTimeframeChange(option.value)}
done

2023-06-12 14:12 UTC, mohammad-akkad approved these changes

2023-06-15 13:52 UTC, merged