[FRONT-97] Filter & Sort Columns
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #59
Opened 2023-06-11 11:47 UTC by ArnoClaude

## Description of Issue
[Linear Task](https://linear.app/la-famiglia-project/issue/FRONT-97/fix-and-finish-table-filtering-and-sorting)

## How I implemented

## Other
I also made the _Edit Column_ dropdown stay open after selecting a column.

2023-06-11 13:38 UTC, kigadye requested changes
Please remove outline on modals similar to updated sidebar/ profile modal + fix padding on the right:
<img width="263" alt="Screenshot 2023-06-11 at 15 37 55" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/14fd1838-5135-456b-b9a9-27637d93ebbc">

Make z-index of topbar greater than that of sidebar or align the modal to the left of the button like the (would prefer the latter, same for filter modal):
<img width="207" alt="Screenshot 2023-06-11 at 15 33 12" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/ed38c424-eccc-4ec1-a5f5-d775a51b7b81">

The edit columns modal now doesn't close when you click outside any more.

2023-06-11 13:38 UTC, kigadye commented on src/components/pure/ProjectsTable/columns.tsx
Please revert to contrib., I know you have a huge screen but most people will use small laptops where it looks kinda ugly if the column title is too big

2023-06-12 12:06 UTC, ArnoClaude commented on src/components/pure/ProjectsTable/columns.tsx
Reverted to `Contrib.`.
Changed z-indices for proper dropdown overlaying.
Regarding the outline, right-padding, and closing modals when clicking outside, I'll tackle that later today, I couldn't get it to work properly just now :)

2023-06-13 10:47 UTC, DamianGrosz2 commented
<img width="197" alt="Bildschirm­foto 2023-06-13 um 12 30 22" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/94179814/33c48e0c-d283-4085-a3ef-2c7614e00825">
- The box could have some more padding.

- This arrow down is a bit unintuitive 
I think ">" and "<" will be enough, the other options would probably not be used anyway. 
So we could do: Stars "greater" 2000 / Stars "less than" 2000

This would solve the arrow problem.

2023-06-13 10:49 UTC, DamianGrosz2 commented
In terms of usability: we could have the delete button outside of the modal, so that it's always visible. Not a must though, what do you think?

2023-06-13 11:00 UTC, DamianGrosz2 commented
I think having a filter for both min and max of a column would be useful. If that's out of scope no worries, then let's add it to improvements.

Other than that, great job!

2023-06-14 11:51 UTC, ArnoClaude commented
> <img alt="Bildschirm­foto 2023-06-13 um 12 30 22" width="197" src="https://user-images.githubusercontent.com/94179814/245447338-33c48e0c-d283-4085-a3ef-2c7614e00825.png">
> * The box could have some more padding.
> * This arrow down is a bit unintuitive
>   I think ">" and "<" will be enough, the other options would probably not be used anyway.
>   So we could do: Stars "greater" 2000 / Stars "less than" 2000
> 
> This would solve the arrow problem.

Agree on the padding. But for the arrow dropdown; Notion does the same. I reckon if Notion does it that way, it probably is fine in terms of UX. What do you think about this? @kigadye 

![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/f8919297-1296-460c-bb1e-696a9843b4fb)

2023-06-14 12:49 UTC, DamianGrosz2 commented
> > <img alt="Bildschirm­foto 2023-06-13 um 12 30 22" width="197" src="https://user-images.githubusercontent.com/94179814/245447338-33c48e0c-d283-4085-a3ef-2c7614e00825.png">
> > * The box could have some more padding.
> > * This arrow down is a bit unintuitive
> >   I think ">" and "<" will be enough, the other options would probably not be used anyway.
> >   So we could do: Stars "greater" 2000 / Stars "less than" 2000
> > This would solve the arrow problem.
> 
> Agree on the padding. But for the arrow dropdown; Notion does the same. I reckon if Notion does it that way, it probably is fine in terms of UX. What do you think about this? @kigadye
> 
> ![image](https://user-images.githubusercontent.com/61106168/245781451-f8919297-1296-460c-bb1e-696a9843b4fb.png)

Ok makes sense, then how about writing the name "greater/less" then the arrow makes sense. Otherwise imo arrow left + arrow down is a bit confusing. @ArnoClaude

2023-06-14 13:52 UTC, ArnoClaude commented
> > > <img alt="Bildschirm­foto 2023-06-13 um 12 30 22" width="197" src="https://user-images.githubusercontent.com/94179814/245447338-33c48e0c-d283-4085-a3ef-2c7614e00825.png">
> > > * The box could have some more padding.
> > > * This arrow down is a bit unintuitive
> > >   I think ">" and "<" will be enough, the other options would probably not be used anyway.
> > >   So we could do: Stars "greater" 2000 / Stars "less than" 2000
> > > This would solve the arrow problem.
> > 
> > 
> > Agree on the padding. But for the arrow dropdown; Notion does the same. I reckon if Notion does it that way, it probably is fine in terms of UX. What do you think about this? @kigadye
> > ![image](https://user-images.githubusercontent.com/61106168/245781451-f8919297-1296-460c-bb1e-696a9843b4fb.png)
> 
> Ok makes sense, then how about writing the name "greater/less" then the arrow makes sense. Otherwise imo arrow left + arrow down is a bit confusing. @ArnoClaude

Even for numeric operators, Notion does it that way :D But sure, I can change that :)
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/6e355a91-dcdb-4463-ac6f-f028cfa6b330)

2023-06-14 23:42 UTC, kigadye submitted a review, later dismissed
Great work overall! Filtering works perfectly. A few code quality and UI improvements are possible though:
- Close modals when clicking outside of them, I believe this was the case before you changed the edit columns modal, so the easiest way would be to undo whatever you did to that, I think the UX isn't too bad if it closes after each click (this should also solve the issue of having 2 models open at the same time)
- Remove the blue outline from modals (just check what I did for the sidebar profile modal)
- Add padding to filter modal and change background color of input to dark grey
- Fix padding on the right of items in filters modal
- Change the options of the timeframe button to today, this week and this month to reflect the GitHub trending categories and hide it on the compare page
- Rename the sorts button to sorting

<img width="216" alt="Screenshot 2023-06-15 at 01 36 42" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/50cc7ce1-fbd1-47e6-b52a-959f0ce84735">

2023-06-14 23:42 UTC, kigadye commented on src/components/page/overview/FilterBar.tsx
> +}
Add newline

2023-06-14 23:42 UTC, kigadye commented on src/components/page/overview/FilterBar.tsx
> +      <p className="text-14 text-gray-500">/&nbsp;25 entries</p>
Make values dynamic (just pass initial & current array lengths down as props)

2023-06-14 23:42 UTC, kigadye commented on src/components/page/overview/Table.tsx
> +      operator === 'ends with')
You can do `Object.values(enum).includes(operator)` instead of this

2023-06-15 20:52 UTC, ArnoClaude commented on src/components/page/overview/Table.tsx
> +      case StringTableFilterOperator.IS:
I prefer long and descriptive names in general. Everyone uses autocomplete anyways.

2023-06-16 14:10 UTC, DamianGrosz2 requested changes
Great job Arno! Overall, looks good to me now, though:
I'm not sure if anybody will ever use not equals as a filter.
Imo we could remove that, and the equals filter aswell?

Also I really think that > is sufficient, why would you also need >=?
That gives the user an unnecessary decision and worsens the UX.

2023-06-16 14:33 UTC, ArnoClaude commented
> Great job Arno! Overall, looks good to me now, though: I'm not sure if anybody will ever use not equals as a filter. Imo we could remove that, and the equals filter aswell?
> 
> Also I really think that > is sufficient, why would you also need >=? That gives the user an unnecessary decision and worsens the UX.

Sure :)

2023-06-16 15:47 UTC, DamianGrosz2 approved these changes
Great

2023-06-16 18:58 UTC, kigadye approved these changes

2023-06-16 19:34 UTC, merged