[META-82] Add sign in with password
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #65
Opened 2023-06-16 10:43 UTC by pczern

2023-06-16 20:37 UTC, kigadye requested changes
Update readme to reflect new environment variables

2023-06-16 20:37 UTC, kigadye commented on src/util/validate.ts
> +  const regex = /\S+@\S+\.\S+/
there are better regex's for email validation

2023-06-16 20:37 UTC, kigadye commented on src/util/validate.ts
> +export const validatePassword = (password: string) => password.length > 6
if we already validate, let's use an at least slightly reasonable policy (e.g. at least uppercase, lowercase, number)

2023-06-16 20:37 UTC, kigadye commented on tailwind.config.js
> +  },
what purpose does this have?

2023-06-16 20:37 UTC, kigadye commented on tailwind.config.js
> +      },
I would add apple system here as well

2023-06-16 20:37 UTC, kigadye commented on src/styles/globals.css
> +  --font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
I would keep apple system first and just remove all the inter imports in the components that should fix the swapping issue

2023-06-16 20:37 UTC, kigadye commented on src/styles/globals.css
> +  font-display: swap;
this would also not be necessary then

2023-06-16 20:37 UTC, kigadye commented on src/pages/_app.tsx
> +      if (typeof window !== 'undefined') return {}
should be `typeof window === 'undefined'`

2023-06-16 20:37 UTC, kigadye commented on src/pages/_app.tsx
> +      const cookie = getCookie(process.env.NEXT_PUBLIC_SUPABASE_AUTH_COOKIE_NAME)
return value of getCookie is array

2023-06-16 20:37 UTC, kigadye commented on src/pages/login.tsx
> +/* eslint-disable tailwindcss/migration-from-tailwind-2 */
remove this

2023-06-16 20:37 UTC, kigadye commented on src/pages/login.tsx
> +                  className="mb-6 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
use color variables instead of hardcoded hex value

2023-06-16 20:37 UTC, kigadye commented on src/pages/login.tsx
> +                  className="mb-4 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
use color variables instead of hardcoded hex value

2023-06-16 20:37 UTC, kigadye commented on src/pages/login.tsx
> +    if (nativeEvent.submitter.value === 'google')
add curly braces for readability

2023-06-16 20:37 UTC, kigadye commented on src/util/cookie.ts
> +// modified from https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/01-cookie/article.md#getcookiename on 16th June 2023, https://github.com/iliakan
the function is not complex enough to require the source, better add comment that explains what the regex matches

2023-06-16 20:37 UTC, kigadye commented on src/util/cookie.ts
> +// modified from https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/01-cookie/article.md#setcookiename-value-options on 16th June 2023, https://github.com/iliakan
remove source here as well

2023-06-16 20:37 UTC, kigadye commented on src/util/cookie.ts
> +// modified from https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/01-cookie/article.md#setcookiename-value-options on 16th June 2023, https://github.com/iliakan
a wise man once said amateurs copy, geniuses steal

2023-06-16 20:37 UTC, kigadye commented on src/util/cookie.ts
> +  console.log(cookie)
remove log

2023-06-16 21:31 UTC, pczern commented on src/pages/login.tsx
> +/* eslint-disable tailwindcss/migration-from-tailwind-2 */
how, disable the rule entirely?

2023-06-16 22:04 UTC, pczern commented on tailwind.config.js
> +  },
when you open devTools you can select colors

2023-06-16 22:04 UTC, pczern commented on src/util/validate.ts
> +export const validatePassword = (password: string) => password.length > 6
I used the same policy as on Supabase platform, where you also set the policy

2023-06-16 22:07 UTC, pczern commented on src/util/validate.ts
> +  const regex = /\S+@\S+\.\S+/
supabase will throw an error if there was a problem, we display the same error
in future we can change it, or you can send me the regex

2023-06-16 22:09 UTC, pczern commented on src/styles/globals.css
> +  --font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
we should keep the inter font first, as long as it is not loaded it will fallback to apple
The inter font is much better and will give same experience on each OS

2023-06-16 22:10 UTC, pczern commented on src/pages/login.tsx
> +                  className="mb-6 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
are we gonna change it again or not?

2023-06-16 22:12 UTC, pczern commented on src/util/cookie.ts
> +// modified from https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/01-cookie/article.md#getcookiename on 16th June 2023, https://github.com/iliakan
the source is required by the author

2023-06-16 22:12 UTC, pczern commented on src/util/cookie.ts
> +// modified from https://github.com/javascript-tutorial/en.javascript.info/blob/master/6-data-storage/01-cookie/article.md#setcookiename-value-options on 16th June 2023, https://github.com/iliakan
experts attribute

2023-06-17 12:14 UTC, kigadye commented on src/util/validate.ts
> +  const regex = /\S+@\S+\.\S+/
Quick Google search gave me this: `/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/`

2023-06-17 12:15 UTC, kigadye commented on src/util/validate.ts
> +export const validatePassword = (password: string) => password.length > 6
then let's also update the policy on Supabase

2023-06-17 12:17 UTC, kigadye commented on tailwind.config.js
> +  },
I don't understand. afaik this just disables the core plugins you listed

2023-06-17 12:18 UTC, kigadye commented on src/styles/globals.css
> +  --font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
ok

2023-06-17 12:20 UTC, kigadye commented on src/pages/login.tsx
> +/* eslint-disable tailwindcss/migration-from-tailwind-2 */
no, fix the problem below

2023-06-17 12:22 UTC, kigadye commented on src/pages/login.tsx
> +                  className="mb-6 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
idk but regardless of that I would avoid custom tailwind values to avoid potential inconsistencies

2023-06-17 13:22 UTC, pczern commented on src/util/validate.ts
> +  const regex = /\S+@\S+\.\S+/
@kigadye you gave me an invalid email regex

2023-06-17 13:27 UTC, pczern commented on src/util/validate.ts
> +export const validatePassword = (password: string) => password.length > 6
oh I just see you only have the validation for min length on supabase

2023-06-17 13:29 UTC, pczern commented on tailwind.config.js
> +  },
I want to be able to change colors in devtools not tailwind color variables, which I can't

2023-06-17 13:35 UTC, pczern commented on src/pages/login.tsx
> +/* eslint-disable tailwindcss/migration-from-tailwind-2 */
<img width="626" alt="image" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/10871302/30af8563-5a3c-4dfa-b98b-0b9f839300a0">
<img width="706" alt="image" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/10871302/2c559eac-837d-4d99-912e-4e4677ed9464">

2023-06-17 13:44 UTC, pczern commented on src/util/validate.ts
> +export const validatePassword = (password: string) => password.length > 6
solved

2023-06-17 13:44 UTC, pczern commented on tailwind.config.js
> +  },
removed

2023-06-17 13:44 UTC, pczern commented on src/pages/login.tsx
> +/* eslint-disable tailwindcss/migration-from-tailwind-2 */
fixed

2023-06-17 13:44 UTC, pczern commented on src/pages/login.tsx
> +                  className="mb-6 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
added lila 400

2023-06-17 13:44 UTC, pczern commented on src/pages/login.tsx
> +                  className="mb-4 block w-full border-b border-solid border-b-indigo-500 bg-transparent font-inter text-gray-100 placeholder-[#8c8fd9]/70 outline-none"
done

2023-06-17 16:08 UTC, kigadye commented on src/util/validate.ts
> +  const regex = /\S+@\S+\.\S+/
alright just use that one then, there's more important things than this

2023-06-18 11:06 UTC, ArnoClaude approved these changes

2023-06-18 11:38 UTC, kigadye approved these changes

2023-06-18 11:38 UTC, merged