[FRONT-132] Sort Table + Smart Green/Red Values + Select Timeframe
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #68
Opened 2023-06-17 13:02 UTC by ArnoClaude

Linear tasks:
https://linear.app/la-famiglia-project/issue/FRONT-132/sort-functionality-for-table
https://linear.app/la-famiglia-project/issue/FRONT-128/smarter-greenred-indicators-for-table-metrics
https://linear.app/la-famiglia-project/issue/FRONT-131/make-select-timeframe-button-functional

2023-06-17 16:04 UTC, kigadye requested changes
very nice but a few improvements are possible

2023-06-17 16:04 UTC, kigadye commented on src/components/page/overview/Table.tsx
> +}
also move filter function above to separate file, forgot to mention in previous review

2023-06-17 16:04 UTC, kigadye commented on src/components/page/overview/TableSortModal.tsx
I think the UX would be much better if the current sorting also gets added into the filterbar (always as first entry) and this model is opened from there, not from the button at the top

2023-06-18 10:21 UTC, kigadye approved these changes

2023-06-18 10:34 UTC, pczern approved these changes
we are on time limit

2023-06-18 10:34 UTC, merged