[FRONT-135]
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #70
Opened 2023-06-18 15:55 UTC by DamianGrosz2

2023-06-19 22:30 UTC, kigadye requested changes

2023-06-19 22:30 UTC, kigadye commented on src/components/pure/TwitterCard.tsx
> +        <div className="border-b border-gray-800 p-4">
add key

2023-06-20 06:26 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Box/LanguagesItem.tsx
> +              className="h-[14px] w-[14px] rounded-full"
done

2023-06-20 06:32 UTC, DamianGrosz2 commented on src/components/pure/TwitterCard.tsx
> +        <div className="border-b border-gray-800 p-4">
done

2023-06-20 14:03 UTC, kigadye requested changes

2023-06-20 14:03 UTC, kigadye commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +              Go to repo
```suggestion
              GitHub
```

2023-06-20 14:03 UTC, kigadye commented on src/components/side-effects/Details/index.tsx
>            <div className="flex flex-row gap-4 border-t border-solid border-gray-800 py-2 pl-7 pr-3">
I would say make the Hackernews card full width and put it first, then put the Twitter cards in a 2 column grid below that

2023-06-20 14:03 UTC, kigadye commented on src/components/side-effects/Details/index.tsx
>  const handleClick = () => ''
delete handleClick and remove from all buttons

2023-06-20 14:40 UTC, DamianGrosz2 commented on src/components/pure/HackernewsCard.tsx
> +          // eslint-disable-next-line react/no-array-index-key
no sometimes they are the same

2023-06-20 14:48 UTC, DamianGrosz2 commented on src/components/pure/Sidebar/Box/FounderItem.tsx
> +          <span className="text-xs not-italic leading-3">Repository count: {repositoryCount}</span>
I think it does, it gives the founders some credibility if its high

2023-06-20 14:53 UTC, DamianGrosz2 commented on src/components/side-effects/Details/index.tsx
>  const handleClick = () => ''
why? then it complains

2023-06-20 15:31 UTC, kigadye commented on src/components/pure/Sidebar/Box/FounderItem.tsx
> +          <span className="text-xs not-italic leading-3">Repository count: {repositoryCount}</span>
hm, not sure, because I think it only counts public repos, and you don't necessarily have to be the owner of a repo to be credible - i.e. I would be far more impressed by someone who has been a major contributor on next.js but has no public repos than some random CS student with 50 public repos of their homework or coding tutorials

2023-06-20 15:32 UTC, kigadye commented on src/components/pure/HackernewsCard.tsx
> +          // eslint-disable-next-line react/no-array-index-key
if they are the same then filter them before to only include unique values, having the same link 3x doesn't make sense

2023-06-20 15:33 UTC, kigadye commented on src/components/side-effects/Details/index.tsx
>  const handleClick = () => ''
onclick shouldn't be a required prop for a button

2023-06-21 00:59 UTC, kigadye approved these changes

2023-06-21 06:49 UTC, DogukanGun requested changes

2023-06-21 06:49 UTC, DogukanGun commented on src/components/page/details/RightSidebar.tsx
> +        <Sidebar.Box.GithubStatItem Icon={StarIcon} value={project.starCount as number} />
Why did you remove null check ? Are you sure that project never becomes null.

2023-06-21 06:49 UTC, DogukanGun commented on src/components/pure/Card.tsx
> +      {variant === 'twitter' && (
Please define twitter value as variable in this component. Like that :
`const twitterVariant = 'twitter'`

Then do your check with twitterVariant

2023-06-21 06:49 UTC, DogukanGun commented on src/components/pure/Sidebar/Box/CompanyItem.tsx
> +        {/* <span className="text-xs not-italic leading-3 text-gray-500">{name}</span>
If you are not going to use this line, please remove it. Comment lines should be used to give information about a code snippet not for hiding not used codes

2023-06-21 06:49 UTC, DogukanGun commented on src/components/pure/Sidebar/Box/FounderItem.tsx
> +  // linkedin?: string
Same as prev comment

2023-06-21 06:49 UTC, DogukanGun commented on src/components/pure/Sidebar/Box/FounderItem.tsx
> +  // linkedin: null,
Same comment

2023-06-21 06:49 UTC, DogukanGun commented on src/components/side-effects/Compare/index.tsx
> +            {/* @TODO Update page title */}
Please move this comment to out of return statement

2023-06-21 06:49 UTC, DogukanGun commented on src/components/side-effects/Compare/index.tsx
> +        {!fetching && !error && data.length > 0 && (
`const funcName = () => !fetching && !error && data.length > 0`

2023-06-21 07:41 UTC, DamianGrosz2 commented on src/components/page/details/RightSidebar.tsx
> +        <Sidebar.Box.GithubStatItem Icon={StarIcon} value={project.starCount as number} />
Yes see Clemens comment on that

2023-06-21 07:54 UTC, ArnoClaude approved these changes
Looks great!

2023-06-21 07:56 UTC, merged