[FRONT-117] Add tooltips
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #72
Opened 2023-06-18 21:27 UTC by yinruo

Description of issue
Add tooltips to some UI components that doesn't have obvious purpose.

How I implemented
npm install react-tooltip
add tooltip to detail page project name. 

Other

2023-06-19 07:55 UTC, ArnoClaude requested changes
Can you put this PR in draft as long as you are still working on it? It just contains a `hello world` tooltip so far.

2023-06-21 06:41 UTC, DogukanGun requested changes

2023-06-21 06:41 UTC, DogukanGun commented on src/components/page/details/RightSidebar.tsx
> +          value={project?.issueCount as number}
If project is empty, what happens here ?

2023-06-21 22:28 UTC, kigadye requested changes
Is there a way to style the tooltips to match our design (i.e. gray background color + 5px border radius)?

2023-06-21 22:28 UTC, kigadye commented on src/components/page/details/RightSidebar.tsx
Capitalize all tooltip values

2023-06-21 22:28 UTC, kigadye commented on src/components/page/details/RightSidebar.tsx
> +          id="fork/contributor"
Forks/ contributor

2023-06-21 22:28 UTC, kigadye commented on src/components/page/details/RightSidebar.tsx
> +          id="issue/contributor"
Issues/ contributor

2023-06-23 01:07 UTC, kigadye approved these changes
Looks great now!

2023-06-23 01:10 UTC, LordZed400 approved these changes

2023-06-23 01:11 UTC, merged