[META-88] Command interface update
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #77
Opened 2023-06-19 15:44 UTC by DogukanGun

Description of Issue
[Linear Task](https://linear.app/la-famiglia-project/issue/META-88/style-update-for-command-interface)

How I implemented
Row type now has restriction param and arrow down and up buttons are now working

2023-06-19 22:03 UTC, kigadye requested changes
When I checkout your branch locally and run it I get the following error:
<img width="985" alt="Screenshot 2023-06-20 at 00 02 04" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/4d8f85c7-d4d8-4fd3-9b8f-d79352809e96">

When I fix that (see comment below), it works, but there seems to be an infinite loop somewhere:
<img width="779" alt="Screenshot 2023-06-20 at 00 01 40" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/57ffea2f-b019-4f1d-8d3f-a35cfbd41eac">

2023-06-19 22:03 UTC, kigadye commented on src/components/side-effects/CommandInterface/index.tsx
> +              project.associatedPerson?.name ?? '',
```suggestion
              project?.associatedPerson?.email ?? '',
              project?.associatedPerson?.name ?? '',
```

2023-06-21 22:36 UTC, kigadye requested changes
Arrow key navigation works, but there are some weird bugs:
- I can't reload the page using Cmd + R anymore
- I can't use Cmd + Backspace to delete the entire line in the CI
- When I go up with the arrow keys, it seems like it goes out of the command interface and keeps counting up, because if I go down again I need to press down the same number of times I went up "out of the CI"
- Sometimes, items do the actions of another one (e.g. settings does logout, logout goes to docs)
- Send email doesn't populate the founder email and name
<img width="255" alt="Screenshot 2023-06-22 at 00 33 06" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/4b6bf868-fd2e-4a6a-9576-8a281e7d978e">

2023-06-22 07:19 UTC, DogukanGun commented
> Arrow key navigation works, but there are some weird bugs:
> 
> * I can't reload the page using Cmd + R anymore
> * I can't use Cmd + Backspace to delete the entire line in the CI
> * When I go up with the arrow keys, it seems like it goes out of the command interface and keeps counting up, because if I go down again I need to press down the same number of times I went up "out of the CI"
> * Sometimes, items do the actions of another one (e.g. settings does logout, logout goes to docs)
> * Send email doesn't populate the founder email and name
> 
> <img alt="Screenshot 2023-06-22 at 00 33 06" width="255" src="https://user-images.githubusercontent.com/37487191/247778691-4b6bf868-fd2e-4a6a-9576-8a281e7d978e.png">
 
I checked the email issue and it is happening because email is not exist in that project. I tried other projects and some of them has an email. Other issues are fixed.
<img width="821" alt="Screenshot 2023-06-22 at 10 18 13" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/59707019/ea6c7f6f-d7cf-4afe-adf7-3bef0b8e6d91">

2023-06-22 10:47 UTC, kigadye requested changes
Most issues are fixed, except when I use the arrow keys to navigate through items and press enter, they still do the wrong actions (e.g. settings does logout, logout goes to docs).

Also, regarding send email for projects that don't have an email, either show a message in the command interface that there is no founder data for this project when the user clicks send email, or just hide the send email option from the CI on those pages.

2023-06-23 00:53 UTC, kigadye commented
Another bug: the CI opens when clicking esc

2023-06-23 09:33 UTC, DogukanGun commented
> Another bug: the CI opens when clicking esc

I will check this. I could not catch the other issue (settings does logout, logout goes to docs) even I tried multiple times. Could you just check your env or try one more time with another browser. Or may be you can share in which page you faced with this issue?

2023-06-23 11:43 UTC, kigadye commented
now the command interface doesn't open at all when I press Cmd/ Ctrl + K

2023-06-23 11:44 UTC, kigadye commented
now the command interface doesn't open at all when I press Cmd/ Ctrl + K

2023-06-25 16:06 UTC, DogukanGun commented
> now the command interface doesn't open at all when I press Cmd/ Ctrl + K

fixed

2023-06-25 21:16 UTC, kigadye requested changes
All of the issues I mentioned above are fixed, but navigating to project details doesn't work

2023-06-26 19:13 UTC, DogukanGun commented
> All of the issues I mentioned above are fixed, but navigating to project details doesn't work

Could you check this video, it is working on me.
https://www.loom.com/share/bd619eee508a425babdb9b0d66fb0199?sid=1b164fb6-4bb7-460d-afea-d8dd94f0a2f5

2023-06-26 21:58 UTC, kigadye requested changes
navigation should work with keyboard only

2023-06-27 21:38 UTC, kigadye approved these changes

2023-06-28 12:59 UTC, ArnoClaude approved these changes
Good job @DogukanGun

2023-06-28 12:59 UTC, merged