[FRONT-138] Fork History in Chart
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #78
Opened 2023-06-20 12:05 UTC by ArnoClaude

## Description of Issue
[Linear Task](https://linear.app/la-famiglia-project/issue/FRONT-138/add-fork-history)
## How I implemented
Added forkHistory to the datasets in Charts.tsx
## Other
For the details page, it's on the left now:
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/387cd565-ca06-41e3-9758-28d243cdf5bc)

2023-06-20 14:10 UTC, kigadye requested changes
- [x] Move forks/ issues dropdown into separate file and update styles to match the ones in the filterbar
- [ ] Fix select timeframe button not working
- [ ] Move forks/ issues button all the way to the left on compare page
- [ ] Fix merge conflicts

2023-06-22 14:00 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                        {TimeframeOptions.map((metric) => (
why is this variable capital case?

2023-06-22 14:01 UTC, pczern commented on src/components/page/details/Chart.tsx
> +                    {['Stars', 'Forks'].map((metric) => (
code smell

2023-06-22 19:28 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +  useEffect(() => {
removed

2023-06-22 19:38 UTC, DamianGrosz2 commented on src/components/side-effects/Compare/index.tsx
> +                      >['datasets'][0]['data'])
done

2023-06-22 19:38 UTC, DamianGrosz2 commented on src/components/side-effects/Details/index.tsx
> +                          typeof Chart
done

2023-06-22 19:42 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +                        {TimeframeOptions.map((metric) => (
done lower

2023-06-22 19:44 UTC, DamianGrosz2 commented on src/components/page/details/Chart.tsx
> +                    {['Stars', 'Forks'].map((metric) => (
@pczern please provide valuable feedback, which one can read without having to google it

2023-06-23 00:45 UTC, kigadye approved these changes
Everything good now, great work!

2023-06-23 00:47 UTC, merged