FRONT-30: Browse Feed List View
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #8
Opened 2023-05-05 07:13 UTC by ArnoClaude

## Description of Issue
[Linear issue.](https://linear.app/la-famiglia-project/issue/FRONT-30/listview-of-overview-page)
## How I implemented
## Other (any extra notes, additional features, problems?, bugs?, performance issues?)

2023-05-09 17:12 UTC, pczern submitted a review, later dismissed
The issue with the class not being applied is, that it is in a `./constants` folder, which is not supplied in the `tailwind.config.js`.

Make sure to delete the folder `./types` for now and move type definitions for enums to `./constants` and to where the objects are being defined

2023-05-09 17:12 UTC, pczern commented on .idea/vcs.xml
remove this file, add to .gitignore

2023-05-09 17:12 UTC, pczern commented on .eslintrc.js
> +    'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }],
this shouldn't be turned off, we have to learn to be proper engineers

2023-05-09 17:12 UTC, pczern commented on .eslintrc.js
> +    'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }],
even I struggle with some; but code quality increases a lot lot

2023-05-09 17:12 UTC, pczern commented on .eslintrc.js
> +        sourceType: 'module'
what is this?

2023-05-09 17:12 UTC, pczern commented on src/constants/tableHelper.tsx
this file should not be in /constants nothing about it is constant!!!

2023-05-09 17:12 UTC, pczern commented on src/constants/tableHelper.tsx
move it  to the actual table, or create a table component and move there in ./components

2023-05-09 17:12 UTC, pczern commented on src/constants/tableHelper.tsx
> +      cell: (info) => <div className="text-sky-300">{info.getValue()}</div>
a <span> might be better

2023-05-09 17:12 UTC, pczern commented on src/types/programmingLanguages.ts
This should be at ./constants, this is constant! We don't define global types in ./src only outside

2023-05-09 17:12 UTC, pczern commented on src/types/repositoryCategories.ts
move to ./constants

2023-05-09 17:12 UTC, pczern commented on src/types/repositoryShort.ts
move to the file where you define it

2023-05-13 21:52 UTC, pczern commented
Can we somehow do a system like 100/200/300/400.... ? and call the colors primary/secondary/tercery? or gray/blue/yellow?
My recent commit messed the colors a little bit up, please try to implement the new naming system and fix

2023-05-13 23:20 UTC, cnk1dev requested changes
There still seems to be an issue with the build, please debug/ fix this:
<img width="1227" alt="Screenshot 2023-05-14 at 01 18 05" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/8cdddc9b-69c9-4988-a289-9deb04dc9618">

2023-05-14 12:40 UTC, cnk1dev approved these changes

2023-05-14 17:06 UTC, merged