FRONT-140 Added pagination to overview page
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #80
Opened 2023-06-20 17:41 UTC by mohammad-akkad

2023-06-21 13:10 UTC, ArnoClaude requested changes
@mohammad-akkad Could you make sure the Vercel Deployment doesn't fail? I'll review later.

2023-06-21 22:49 UTC, kigadye requested changes
Very nice! Couple things could be improved though:

- [ ] Set the page size/ number of entries per request back to 30 (pagination should only apply for pages that have more than 30 results)
- [ ] Change the appearance of the prev/ next buttons if they're disabled (just like details page nav)
- [ ] Either find a way to display current + total number of entries/ pages in filterbar, or remove "showing 5/5 entries"

2023-06-22 10:40 UTC, kigadye requested changes
- [x] Don't show next/ prev buttons if there is only 1 page
- [x] Remove all added eslint ignore rules and fix the underlying issues if any
- [ ] Total count sometimes doesn't update when you change filters (probably due to caching). Also, I saw you're just using the length of the query result without pagination, but that would always return 30 at most, which is the issue we had previously. Idk how to fix this off the top of my head and it's not prio 1 for the demo so I would say just leave the total count as it was before, i.e. use the length of the filtered query with pagination although it's wrong and add a `@TODO` comment to fix it later.

2023-06-22 18:45 UTC, ArnoClaude requested changes
Good stuff @mohammad-akkad . Left you three small improvement suggestions :)

2023-06-22 18:45 UTC, ArnoClaude commented on src/components/page/details/RightSidebar.tsx
> +      {project.languages?.length && project.languages?.length > 0 && (
`project.languages?.length` is enough

2023-06-22 18:45 UTC, ArnoClaude commented on src/components/page/overview/FilterBar.tsx
> +      last: 30,
magic number, could be `PAGE_SIZE`

2023-06-22 18:45 UTC, ArnoClaude commented on src/components/page/overview/FilterBar.tsx
> +  return (
Currently, all FilterItemModal are being created at each render. Consider using useMemo to prevent unnecessary rerendering if the filters and updateFilters props haven't changed.

```
const filterItemModals = useMemo(() => {
  return Object.keys(filters)
    .filter((key) => !Object.values(TimeFilterOption).includes(key as TimeFilterOption))
    .map((key) => (
      <FilterItemModal
        key={key}
        currentKey={key as FilterOption['key']}
        filters={filters}
        updateFilters={updateFilters}
      />
    ))
}, [filters, updateFilters]);

// Then, in your render...
<div className="flex flex-row gap-3">
  {sorting && <SortModal sorting={sorting} setSorting={setSorting} />}
  {sorting && Object.keys(filters).length > 0 && <div className="my-auto h-4/5 border-l border-gray-800" />}
  {filterItemModals}
</div>

```

2023-06-27 13:50 UTC, ArnoClaude requested changes
Awesome job. Left one remark :)

2023-06-27 13:50 UTC, ArnoClaude commented on src/pages/bookmarks.tsx
> +  const [{ data: urqlDataTotal }] = useTrendingProjectsQuery({
Perhaps I'm missing something, but is this second call to `useTrendingProjectsQuery` necessary? Can't you get the total amount of rows from the other `useTrendingProjectsQuery` call?

2023-06-27 14:01 UTC, mohammad-akkad commented on src/pages/bookmarks.tsx
> +  const [{ data: urqlDataTotal }] = useTrendingProjectsQuery({
good catch, yeah I removed the pagination params as they affect the total count, otherwise we can yeah as you said use the same one

2023-06-27 23:39 UTC, kigadye requested changes
When I run the project locally I get the following error:
<img width="993" alt="Screenshot 2023-06-28 at 01 38 35" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/37487191/ffe30de9-49fa-4b1e-b8ca-158e315347f1">

2023-06-27 23:39 UTC, kigadye commented on src/pages/index.tsx
> +      ...pagination
I believe this doesn't make sense because Supabase returns max 30 entries in any case, and it's just the same query as the one before, so you're doubling the data you fetch but don't get any additional information. Not sure if/ how it's possible to get the total count from Supabse, so let's just remove the unnecessary query and use the length of the current page for now

2023-06-27 23:39 UTC, kigadye commented on src/components/side-effects/Details/index.tsx
> +            about={(project.about as string) || 'No description'}
no need to cast to string here because we have a fallback - if about is not present we want to show "no description", not an empty string

2023-06-27 23:39 UTC, kigadye commented on src/components/side-effects/Compare/index.tsx
> +    first: 10,
should probably use `PAGE_SIZE` instead of `10` here

2023-06-29 20:49 UTC, kigadye approved these changes

2023-06-29 20:53 UTC, pczern approved these changes
needed for handover tomorrow

2023-06-29 20:54 UTC, merged