[FRONT-128] Smart Green/Red Values in Table
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #83
Opened 2023-06-21 08:28 UTC by ArnoClaude

## Description of Issue
The user wants an easy way to quickly find out if a value is good compared to the other value for that column/metric.
## How I implemented
Changed the columns const to a function that returns those columns, such that I could inject the top/bottom ten percent calculated in the Compare and Overview page.
## Other

2023-06-21 09:50 UTC, mohammad-akkad approved these changes

2023-06-21 09:50 UTC, mohammad-akkad commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  console.log(redValue)
do you need these consoles

2023-06-21 11:06 UTC, ArnoClaude commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  console.log(redValue)
forgot these, thanks!

2023-06-21 22:42 UTC, kigadye requested changes
Could we do more than just the top/ bottom 10%? Because right now it's only about 2-3 repos that get colored on the trending page.

Also, could you add a lighter shade of green/ red for the next 10-20% below/ above the top/ bottom 10-20% to make the colors even more useful?

2023-06-22 12:20 UTC, ArnoClaude commented
> Could we do more than just the top/ bottom 10%? Because right now it's only about 2-3 repos that get colored on the trending page.
> 
> Also, could you add a lighter shade of green/ red for the next 10-20% below/ above the top/ bottom 10-20% to make the colors even more useful?

![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/be169cd2-3361-4e5c-90b4-bf50136dc5ae)
Done

2023-06-22 13:15 UTC, pczern reviewed
I don't approve of the PR for code duplication, type duplication, React state violation, bad type casting, too many array key indexes instead of .maps and .reduce, client side js sorting
it will greatly affect the maintainability for every future contributor

2023-06-22 13:15 UTC, pczern commented on src/components/side-effects/ProjectsTable/columns.tsx
> +          greenValue={bottomTenPercent.pullRequestCount as number}
why all these casts, we want to prevent that as much as possible

2023-06-22 17:20 UTC, ArnoClaude commented on src/components/side-effects/Compare/index.tsx
> +        .sort((a, b) => b - a)
This sorting doesn't affect the UI, it is needed only here to get the percentiles.

2023-06-22 17:27 UTC, ArnoClaude commented on src/components/side-effects/ProjectsTable/columns.tsx
> +          greenValue={bottomTenPercent.pullRequestCount as number}
Because GraphQL returns Maybe<number | undefined>. Alternatively, you could provide a default value:
```
<GitHubStatisticItem
  Icon={VscIssues}
  paddingOn={false}
  outerPaddingOn={false}
  value={info.getValue() ?? 0}
  greenValue={bottomTenPercent.issueCount ?? 0}
  lightGreenValue={topTwentyPercent.issueCount ?? 0}
  redValue={topTenPercent.issueCount ?? 0}
  lightRedValue={bottomTwentyPercent.issueCount ?? 0}
/>
```
I don't know any elegant solutions.

2023-06-22 17:34 UTC, ArnoClaude commented on src/components/side-effects/ProjectsTable/columns.tsx
> +    columnHelper.accessor('forkCount', {
Idk if it would make the code more readable, as it only concerns half the columns :/ Can this be looked at in a follow-up clean-up PR if necessary?

2023-06-22 17:34 UTC, ArnoClaude commented on src/components/side-effects/Compare/index.tsx
> +  const [topTwentyPercent, setTopTwentyPercent] = useState<{
Agree, done

2023-06-22 17:36 UTC, ArnoClaude commented on src/components/side-effects/Compare/index.tsx
> +    const numericFields: (keyof Project)[] = [
You mean `keyof Project` or anything else? Anyhow, I tried to reduce some unneeded explicit typing now :)

2023-06-22 17:44 UTC, ArnoClaude commented on src/components/pure/Sidebar/Box/GithubStatItem.tsx
> +  lightGreenValue,
Yeah, that would be cleaner. Though that's been this way for a while and not a part of this PR. I'll keep a note for a cleanup PR, but we need this feature tomorrow.

2023-06-22 18:17 UTC, ArnoClaude commented on src/components/side-effects/Compare/index.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
any ideas how to fix this?

2023-06-22 18:17 UTC, ArnoClaude commented on src/components/side-effects/ProjectsTable/index.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
any ideas how to fix this?

2023-06-27 13:51 UTC, closed without merging