[FRONT-142] Replace calculated values with provided, add to filtering and sorting
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #85
Opened 2023-06-22 14:36 UTC by WrappedSuperClass

## Description of Issue
The forksPerContr and the issuesPerContributer are calculated in the frontend. Remove the calculation and use instead the newly added attributes provided from the backend
## How I implemented
Edited the query, as i'm using windows, i had to change the script in codegen.config.ts, but the changes were not commited and/or pushed. 

With the new props of project i replaced the calculated one in the right sidebar and in the table. 

I added the new attributes as filter and sorting options, and replaced the parseInt with parseFloat to make the filter work for the new attributes too
## Other

2023-06-22 18:26 UTC, ArnoClaude requested changes
Great job Lukas! I just left two small remarks :)

2023-06-22 18:26 UTC, ArnoClaude commented on src/components/page/details/RightSidebar.tsx
>          <Sidebar.Box.GithubStatItem
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/a0515c45-fbc1-49a5-9f28-1136afa11f96)
Contributors should be 0, not empty.
Also, can you re-order the icons such that it's either Issues, Issues/Contrib., Forks, Forks/Contrib.?

2023-06-22 18:26 UTC, ArnoClaude commented on src/components/page/details/RightSidebar.tsx
>          <Sidebar.Box.GithubStatItem
![image](https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/a0515c45-fbc1-49a5-9f28-1136afa11f96)
Contributors should be 0, not empty.
Also, can you re-order the icons such that it's Issues, Issues/Contrib., Forks, Forks/Contrib.?

2023-06-28 00:01 UTC, kigadye approved these changes

2023-06-28 00:01 UTC, kigadye commented on src/components/page/details/RightSidebar.tsx
>          <Sidebar.Box.GithubStatItem
done

2023-06-29 20:38 UTC, pczern approved these changes
needed for handover tomorrow

2023-06-29 20:40 UTC, merged