[FRONT-144] Add new text to doc, create new component
jst-seminar-rostlab-tum/truffle-ai-frontend pull request #90
Opened 2023-06-28 23:05 UTC by WrappedSuperClass

## Description of Issue
Using the documentation and the UI of truffle.tools add a documentation page
## How I implemented
Creating reusable react components i tried to recreated the documentation with the existing text

## Other

2023-07-01 09:12 UTC, ArnoClaude requested changes
Looks really good to me. Just two improvement suggestions:
Increase the top space for a new section:
<img width="305" alt="image" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/37111750-c97b-4db6-97fc-b0e544296498">

Remove the "User Manual" text, and replace it by a short pre-phase, explaining what this documentation page is about (it explains the individual pages in the app)
<img width="509" alt="image" src="https://github.com/jst-seminar-rostlab-tum/truffle-ai-frontend/assets/61106168/3192406b-0945-4ad0-a3c9-0107ef6afed8">

2023-07-04 12:41 UTC, pczern commented on src/components/page/docs/Heading.tsx
> +const headingClasses = (type: HeadingProps['type'], customClasses: string) => {
looks like a Map

2023-07-04 12:42 UTC, pczern approved these changes

2023-07-04 13:47 UTC, ArnoClaude approved these changes

2023-07-04 20:51 UTC, kigadye commented
@pczern thanks for the suggestions, will still merge now due to limited time but keep them in mind for future improvements

2023-07-04 20:51 UTC, merged